### ISSUE TITLE
ModuleNotFoundError: No module named 'model' in getting start guide

### ISSUE THREAD

**Issue by allen-ng** [GoogleCloudPlatform/cloudml-samples#101]
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: Python 3.6.2 :: Anaconda custom (64-bit)
- **Exact command to reproduce**:
```
gcloud ml-engine local train \
--module-name trainer.task \
--package-path trainer/ \
-- \ 
--train-files $TRAIN_DATA \
--eval-files $EVAL_DATA \
--train-steps 1000 \
--job-dir $MODEL_DIR \
--eval-steps 100
```

- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```

### Describe the problem
I tried to run the consensus trainer locally as in example https://cloud.google.com/ml-engine/docs/getting-started-training-prediction
But got `ModuleNotFoundError: No module named 'model'` from task.py.
I ran the command under `/home/allen/working/gcp/cloudml-samples-master/census/estimator
`.
The directory is like:
```
.
├── data
│   ├── adult.data.csv
│   └── adult.test.csv
└── trainer
    ├── __init__.py
    ├── model.py
    ├── __pycache__
    └── task.py

3 directories, 5 files
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

The trace back information is like:
```
Traceback (most recent call last):
  File "/home/allen/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/allen/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/allen/working/gcp/cloudml-samples-master/census/estimator/trainer/task.py", line 4, in <module>
    import model
ModuleNotFoundError: No module named 'model'
```

Thanks

**Comment by puneith** [comment]
Can you please paste your pwd? Just to make sure you haven't cd-ed into trainer?

**Comment by allen-ng** [comment]
Thank you, the full sequence is like this:
```
allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ source activate tensorflow
(tensorflow) allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ echo $PWD
/home/allen/working/gcp/cloudml-samples-master/census/estimator
(tensorflow) allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ echo $TRAIN_DATA
/home/allen/working/gcp/cloudml-samples-master/census/estimator/adult.data.csv
(tensorflow) allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ echo $EVAL_DATA
/home/allen/working/gcp/cloudml-samples-master/census/estimator/adult.test.csv
(tensorflow) allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ echo $EVAL_DATA
/home/allen/working/gcp/cloudml-samples-master/census/estimator/adult.test.csv
(tensorflow) allen@sy:~/working/gcp/cloudml-samples-master/census/estimator$ gcloud ml-engine local train --module-name trainer.task --package-path trainer -- --train-files $TRAIN_DATA --eval-files $EVAL_DATA --train-steps 1000 --job-dir $MODEL_DIR --eval-steps 100
Traceback (most recent call last):
  File "/home/allen/anaconda3/envs/tensorflow/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/allen/anaconda3/envs/tensorflow/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/allen/working/gcp/cloudml-samples-master/census/estimator/trainer/task.py", line 4, in <module>
    import model
ImportError: No module named 'model'

```

**Comment by puneith** [comment]
Ok I am going to assume you are using Python3 conda env? If that's the case then we have a known bug in gcloud where it uses python2 even if invoked from virtual/conda py3 and I am sure that's using wrong PYTHONPATH. Can you please run this on py2 (conda/virtual) and see if same problem exists.

**Comment by allen-ng** [comment]
It works fine now with a newly created python 2.7 environment.
Thank you! :)

**Comment by sunilpankaj** [comment]
i got this error

Traceback (most recent call last):
  File "C:/Users/anil pankaj/Documents/neural network/facial_detection_practice.py", line 1, in <module>
    from model import create_model
ModuleNotFoundError: No module named 'model'

on this code to mention below

from model import create_model
nn4_small2 = create_model()

so how to resolve it.

**Comment by ricoms** [comment]
@puneith Does this known bug still exist?

**Comment by ultrons** [comment]
I second @ricoms question. I notice the same problem with python3.5 environment.

**Comment by ricoms** [comment]
@ultrons, I solved it by using reference import, like this:
```python
import trainer.model as model
```

here it worked, I'm onto new bugs now xD
