### ISSUE TITLE
Update serving input functions

### ISSUE THREAD

**Issue by thedriftofwords** [GoogleCloudPlatform/cloudml-samples#108]
@nkashy1 For Census sample, update serving input functions from `tf.contrib.learn.InputFnOps` to `tf.estimator.export.ServingInputReceiver` when ML Engine adds support for TF 1.4.

**Comment by puneith** [comment]
This is already done in this PR https://github.com/GoogleCloudPlatform/cloudml-samples/pull/95. We will merge it when Cloud ML Engine has TF1.4 next week.
