### ISSUE TITLE
generate_input_fn(...) does not have return signature function () -> (features, indices)

### ISSUE THREAD

**Issue by zaffnet** [GoogleCloudPlatform/cloudml-samples#116]
As per line 286 of census/estimator/trainer/model.py, the function `generate_input_fn(...)` should return a function () -> (features, indices). Instead the function is returning (features, labels). Also, the function is not "generating" some `input_fn`.

### System information
- Linux Ubuntu 16.04
- Tensorflow 1.4

**Comment by puneith** [comment]
Good catch! I see this is a code documentation issue here. Can you please send a PR. Closing this issue.

**Comment by zaffnet** [comment]
I am currently working to fix the documentation. I will send a PR soon.
