### ISSUE TITLE
Keras Census - generator_input stuck in the first file chunk

### ISSUE THREAD

**Issue by RemiTurpaud** [GoogleCloudPlatform/cloudml-samples#119]
I may be missing the obvious, but it seems that the generator_input function for the Keras model.py indefinitely iterates over the first file chunk.
The reason is that the function returns a count() iterator within the first iteration of the file read loop:

census/keras/trainer/model.py

```
input_reader = pd.read_csv(tf.gfile.Open(input_file[0]), chunksize=chunk_size [...])
for input_data in input_reader:
       [...]
       n_rows = input_data.shape[0]
       return ( (input_data.iloc[[index % n_rows]], label.iloc[[index % n_rows]]) for index in itertools.count() )

```
It seems the issue was introduced with the PR #69 
 
Toy example:

```
CSV_COLUMNS=['x','y']
LABEL_COLUMN='y'
filename='test.csv'
pd.DataFrame({'X':['A','B','C','D'],'Y':[1,2,3,4]}).to_csv(filename,index=False,header=False)

def generator_input(input_file, chunk_size):
  """Generator function to produce features and labels
     needed by keras fit_generator.
  """
  input_reader = pd.read_csv(tf.gfile.Open(input_file[0]),
                           names=CSV_COLUMNS,
                           chunksize=chunk_size,
                           na_values=" ?")

  for input_data in input_reader:
    input_data = input_data.dropna()
    label = pd.get_dummies(input_data.pop(LABEL_COLUMN))

    n_rows = input_data.shape[0]
    return ( (input_data.iloc[[index % n_rows]], label.iloc[[index % n_rows]]) for index in itertools.count() )
    

g=generator_input([filename],2)
for i in g:
    print(i[0])

```

**Comment by puneith** [comment]
The Keras generator(..) is supposed to be iterating over the data indefinitely, but are you saying the data is indefinitely returned over only first chunk?

**Comment by RemiTurpaud** [comment]
Precisely!
I don't really have a smart solution though. The simplest would probably be to revert PR #69 and place the whole file reader loop into an infinite loop. So you  read the file over and over...

**Comment by RemiTurpaud** [comment]
Here is an idea: PR #127

**Comment by puneith** [comment]
@RemiTurpaud Sorry about the delay. I have commented on the PR as well, I will take a look at the code and will get back to you.

**Comment by puneith** [comment]
@RemiTurpaud Your PR #127  looks good, so closing this. Thanks again!
