### ISSUE TITLE
No iteritems in python3

### ISSUE THREAD

**Issue by happyhuman** [GoogleCloudPlatform/cloudml-samples#123]
I ran this code on my computer. It ran fine using Python 2, but because Python 3 is no longer supporting iteritems() for dictionaries, the following line of code failed.

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/fc74d1f551eff1ea4d219195f048634ff6f7b40d/census/estimator/trainer/model.py#L237

**Comment by puneith** [comment]
Fixing the issue in the PR.
