### ISSUE TITLE
Preprocessing for online predictions

### ISSUE THREAD

**Issue by rajhans** [GoogleCloudPlatform/cloudml-samples#14]
Hello

This is more of a question than a request.. or could be construed as a feature request. We are in the process of setting up google cloud ml for a case where we need online predictions for a text classification problem. From google cloud ml documentation, it seems like making a REST api call to a deployed model might be the way to go.

However, the documentation is unclear on what kind of preprocessing can be supported in the deployed model in the online setting. We plan to pass a dictionary of {string:double} features (think TFIDF) and let the model take care of preprocessing like converting words to corresponding indices. In this case, one way is to have specific ops in my tensorflow graph that convert strings to corresponding features and specify 'inputs' collection appropriately. However, for more complex features, doing feature wrangling inside a tensorflow graph quickly becomes tedious. Is there anyway to specify a custom preprocessing step for *online* prediction before the tensorflow graph is invoked? 

While the iris code write by @joshgc was super helpful, it also does preprocessing *before* making a batch prediction call to the deployed model, which we are trying to avoid.

Thanks!
Rajhans

p.s. Hey Josh... nice work! :)

**Comment by joshgc** [comment]
Hey Rajhans!  Thanks for the props, but its definitely a team effort over here =)

I've looped in a preprocessing expert to give you the most up-to-date answer.

**Comment by rajhans** [comment]
Thanks for the response, Josh! I have changed my code to perform all the processing inside my TF graph for now (so I'm now passing raw strings to the 'inputs'). So while it will definitely be useful to know if it is possible to perform preprocessing before online inference, it is not urgent anymore.

Best,
Rajhans

**Comment by joshgc** [comment]
Great glad to hear it, this is the approach for flowers/ as well.  I think there are many advantages to just using a TF model if the ops you need are already there.  The serving system can just make many more optimizations based on the tighter assumptions of it only needing to host 1 TF model.

I'll leave this issue open for a couple days, then close it unless I hear otherwise.

**Comment by rajivpb** [comment]
Yes, the platform has been designed to replay the same preprocessing that's run before training/batch-prediction (i.e. during the preprocess step) at the time of online prediction. 

A "spec" of the preprocessing is saved via:
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/iris/preprocess.py#L110

If you follow the steps in the sample and save the metadata and the features in the right locations, then the same preprocessing functionality is invoked on the raw instance during online prediction, _before_ the tensorflow graph is invoked. 

Does this address your concern?

A few caveats: 

1. Only preprocessing functionality in the Cloud ML SDK can be used in this fashion. In our alpha release, do not have a way of replaying "truly" custom preprocessing functionality that's outside the SDK. 

2. The Cloud ML SDK handles many wide and common cases (including TF-IDF) for text features. If there were any specific feature asks that you had, please let us know.

**Comment by rajhans** [comment]
Great -- this is definitely useful and works for now. I have one more question, which I'm filing as a separate ticket.

**Comment by jcomfort4** [comment]
@rajivpb the sample you have pointed to seems to have been deprecated: https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/iris/preprocess.py#L110

Is there a more recent example that is not deprecated that would demonstrate the best way to perform this behavior or more up to date bes tpractices?
