### ISSUE TITLE
It doesn't work with modified data

### ISSUE THREAD

**Issue by gzd2** [GoogleCloudPlatform/cloudml-samples#145]
[adult.data.csv.tar.gz](https://github.com/GoogleCloudPlatform/cloudml-samples/files/1617709/adult.data.csv.tar.gz)
[adult.data.csv.tar.gz](https://github.com/GoogleCloudPlatform/cloudml-samples/files/1617712/adult.data.csv.tar.gz)

For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7.12
- **Exact command to reproduce**: gcloud ml-engine local train     --module-name trainer.task     
--package-path trainer/     --job-dir $MODEL_DIR     --     --train-files $TRAIN_DATA     --eval-files $EVAL_DATA     --train-steps 1000     --eval-steps 100

- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
the sample code, and whether it occurred locally or on the server (CloudML Engine,
Google Dataflow)

I tried original code with original adult data, it worked. But when I deleted 2 rows from the data, the following error was occured. (I sent my adult.data.csv)

InvalidArgumentError (see above for traceback): assertion failed: [Label IDs must >= 0] [Condition x >= 0 did not hold element-wise:] [x (head/ToFloat:0) = ] [[-1][-1][-1]...]
	 [[Node: head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert/Switch, head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert/data_0, head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert/data_1, head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert/data_2, head/assert_range/assert_non_negative/assert_less_equal/Assert/AssertGuard/Assert/Switch_1)]]

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by puneith** [comment]
I see the data looks weird. It won't work because the class label is incorrect. 

39, State+AC0-gov,77516, Bachelors,13, Never+AC0-married, Adm+AC0-clerical, Not+AC0-in+AC0-family, White, Male,2174,0,40, United+AC0-States, +ADwAPQ-50K

**Comment by gzd2** [comment]
I used LibreOffice Calc to modify data. Modified data looks accurate when I open with LibreOffice Calc, but you are right, it looks wrong when I open with other programs.
Thanks

**Comment by gzd2** [comment]
I solved the problem by changing encoding. But now, I deleted 3rd column and I updated model.py as following:

CSV_COLUMNS = ['age', 'workclass', 'education', 'education_num',
               'marital_status', 'occupation', 'relationship', 'race', 'gender',
               'capital_gain', 'capital_loss', 'hours_per_week',
               'native_country', 'income_bracket']
CSV_COLUMN_DEFAULTS = [[0], [''], [''], [0], [''], [''], [''], [''], [''],
                       [0], [0], [0], [''], ['']]

There is no need any other modification on model.py, becouse 3rd column is not used already. 
When I tried with this data (I sent as attachment), the following error was occured.

 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING], field_delim=",", na_value="", use_quote_delim=true](ExpandDims, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_1, DecodeCSV/record_defaults_2, DecodeCSV/record_defaults_3, DecodeCSV/record_defaults_4, DecodeCSV/record_defaults_5, DecodeCSV/record_defaults_6, DecodeCSV/record_defaults_7, DecodeCSV/record_defaults_8, DecodeCSV/record_defaults_9, DecodeCSV/record_defaults_10, DecodeCSV/record_defaults_11, DecodeCSV/record_defaults_12, DecodeCSV/record_defaults_13)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1], [?,1]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_STRING, DT_INT32, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]


[adult.data.csv.tar.gz](https://github.com/GoogleCloudPlatform/cloudml-samples/files/1617887/adult.data.csv.tar.gz)

**Comment by puneith** [comment]
Don't change the CSV columns because that's the header for the input. Change anything you want to in the INPUT_COLUMNS.

**Comment by gzd2** [comment]
Yes, I solved the problem, thanks. But now, I am trying with different dataset. It works when there is 2 different unique class labels. But when there are 9 different unique class labesl, the following error is occurred.

InvalidArgumentError (see above for traceback): assertion failed: [Label IDs must < n_classes] [Condition x < y did not hold element-wise:x (head/ToFloat:0) = ] [[5][1][1]...] [y (head/assert_range/Const:0) = ] [2]

which part of the model.py should I modify to solve this problem?
