### ISSUE TITLE
Movielens Preprocessing

### ISSUE THREAD

**Issue by beatgeek** [GoogleCloudPlatform/cloudml-samples#148]
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/89bb90e14972aeb56102e90c1ab1442b573755c2/movielens/preprocess.py#L168

This line throws a syntax error as:

`File "preprocess.py", line 168
    def process(self, (user_id, user_ratings),
                      ^
SyntaxError: invalid syntax`

in both local and cloud run

**Comment by beatgeek** [comment]
seems to be a parenthesis issue with this line, line 328 and 363. After that the script begins to execute so far...

**Comment by puneith** [comment]
@beatgeek We are working on upgrading this to TF1.4 so these warnings should go away. But in the mean time it looks like it worked for you when you made a change? Appreciate if you can you please send a PR with the fix.

**Comment by beatgeek** [comment]
@puneith  yes my fix worked - I'll send a PR with fix. Apologies for the delay in getting back.

**Comment by puneith** [comment]
Adam thanks for your work, closing this issue.
