### ISSUE TITLE
Missing self in flowers adaptive_wait method

### ISSUE THREAD

**Issue by maysamemadi** [GoogleCloudPlatform/cloudml-samples#15]
Looks like there is a small error in the flowers example pipeline module. I know you currently don't accept contributions, so I'll just point it out here.

The [prediction attempt](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/flowers/pipeline.py#L329) called from the `adaptive_wait` method as part of `deploy_model` is missing a `self`. As a result, after successful deployment of the model, prediction attempts will quietly fail until max wait time is exceeded. Changing that line to `self.predict(self.args.sample_image_uri)` should fix it.

**Comment by joshgc** [comment]
Thanks for the heads up, we will get this rolled into the next release

**Comment by joshgc** [comment]
Just committed the code, so I'll close the issue, but please let me know about anything else you find!
