### ISSUE TITLE
census local train --job-dir: Must be of form gs://bucket/object

### ISSUE THREAD

**Issue by dwujellyfish** [GoogleCloudPlatform/cloudml-samples#152]
I tried the census sample code in GCP compute engine with:
`gcloud ml-engine local train \
    --module-name trainer.task \
    --package-path trainer/ \
    --job-dir $MODEL_DIR \
    -- \
    --train-files $TRAIN_DATA \
    --eval-files $EVAL_DATA \
    --train-steps 1000 \
    --eval-steps 100`

I got an error: 
> (gcloud.ml-engine.local.train) argument --job-dir: Must be of form gs://bucket/object

Here is my SDK version
Google Cloud SDK 162.0.1
alpha 2017.07.13
beta 2017.07.13
bq 2.0.24
core 2017.07.13
gcloud 
gsutil 4.27

I am using tensorflow version 1.4.0

**Comment by puneith** [comment]
@dwujellyfish I assume your current MODEL_DIR is a local FS path?

**Comment by dwujellyfish** [comment]
Yes, it is local on a GCP compute engine.  
I actually tried to install virtualenv and tensorflow on another compute engine, and it seems to work fine.  So I am assuming may be it was some outdated versions previously.

**Comment by puneith** [comment]
Okay I am going to close this issue in that case. Please feel free to re-open this one or open another issue if it persists.
