### ISSUE TITLE
IN ANDROID OVERLAY PROBLEM

### ISSUE THREAD

**Issue by paneem** [GoogleCloudPlatform/cloudml-samples#156]
import android.app.Service;
import android.content.Intent;
import android.graphics.PixelFormat;
import android.graphics.PointF;
import android.os.IBinder;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.View.OnTouchListener;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Toast;

import de.mobilej.overlay.R;

public class OverlayShowingService extends Service implements OnTouchListener, OnClickListener
{

    static int x,y,r=255,g=255,b=255;
    final static int radius=30;

    private View topLeftView;

    private Button overlayedButton;
   ImageView  iv;
    private WindowManager wm;
    float downx = 0, downy = 0, upx = 0, upy = 0;
    drawingView dview;

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onCreate() {
        super.onCreate();

        dview=new drawingView(this);
        LinearLayout oView;

        //dv = new DrawingView(this);
        //dv.setOnClickListener(this);

    iv  = new ImageView(this);
        iv.setImageResource(R.drawable.star);
        iv.setMaxHeight(10);
        iv.setMaxWidth(10);
        iv.setScaleType(ImageView.ScaleType.MATRIX);

/*

        wm = (WindowManager) getSystemService(Context.WINDOW_SERVICE);

        overlayedButton = new Button(this);

        oView = new LinearLayout(this);
        oView.setBackgroundColor(0x88ff0000);

      //  overlayedButton.setText("Overlay button");
        overlayedButton.setOnTouchListener(this);
        overlayedButton.setAlpha(0.0f);
        overlayedButton.setBackgroundResource(R.drawable.star);
        overlayedButton.setOnClickListener(this);

*//*

        WindowManager.LayoutParams params = new WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                        |WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                        |WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,
                PixelFormat.TRANSLUCENT);

        params.gravity = Gravity.RIGHT | Gravity.TOP;
*//*

        WindowManager.LayoutParams params = new WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.MATCH_PARENT, WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE, PixelFormat.TRANSLUCENT);

        params.gravity = Gravity.CENTER; //| Gravity.CENTER;
        params.x = 0;
        params.y = 0;
       wm.addView(dview, params);*/

        WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.TYPE_SYSTEM_ERROR,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE |
                        WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,
                PixelFormat.TRANSPARENT);

        params.gravity = Gravity.TOP | Gravity.CENTER_HORIZONTAL;
        WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);
        wm.addView(dview, params);

        topLeftView = new View(this);
        WindowManager.LayoutParams topLeftParams = new WindowManager.LayoutParams(WindowManager.LayoutParams.WRAP_CONTENT, WindowManager.LayoutParams.WRAP_CONTENT, WindowManager.LayoutParams.TYPE_SYSTEM_OVERLAY, WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL, PixelFormat.TRANSLUCENT);
        topLeftParams.gravity = Gravity.LEFT | Gravity.TOP;
        topLeftParams.x = 0;
        topLeftParams.y = 0;
        topLeftParams.width = 0;
        topLeftParams.height = 0;
        wm.addView(topLeftView, topLeftParams);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (overlayedButton != null) {
            wm.removeView(overlayedButton);
            wm.removeView(topLeftView);
            overlayedButton = null;
            topLeftView = null;
        }
    }

**Comment by puneith** [comment]
@paneem This issue is not relevant for this repo.
