### ISSUE TITLE
Add package installation instructions to "Setup" section in scikit-learn online prediction notebook

### ISSUE THREAD

**Issue by nkashy1** [GoogleCloudPlatform/cloudml-samples#163]
Right now, users have to look through the `import` statements in the cells to figure out what packages they should install in their Python environment. It would be more convenient if the dependencies were stated explicitly up front.

We should also consider adding a `requirements.txt`.

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/cloudml-samples/pull/169
