### ISSUE TITLE
Add link to cloudml-template in top-level README

### ISSUE THREAD

**Issue by nkashy1** [GoogleCloudPlatform/cloudml-samples#165]
@ksalama : Do you want to take this on?

@thedriftofwords : Can you help Khalid with this? Are we going to refer to the template in the ML Engine docs?

**Comment by nkashy1** [comment]
Resolved by https://github.com/GoogleCloudPlatform/cloudml-samples/pull/167

**Comment by thedriftofwords** [comment]
@nkashy1 Yes, this week I will discuss with the other TWs where we'd like to add it.
