### ISSUE TITLE
Add optional results verification step to scikit-learn online prediction notebook

### ISSUE THREAD

**Issue by thedriftofwords** [GoogleCloudPlatform/cloudml-samples#168]
The XGBoost notebook has a good "optional step 6" part to verify the results and compare the predictions from the local model with those from the online one. Can we modify that and add it to the scikit-learn notebook? (@nnegrey)

**Comment by nnegrey** [comment]
Yep! Will get that updated today.

**Comment by nnegrey** [comment]
https://github.com/GoogleCloudPlatform/cloudml-samples/pull/169
