### ISSUE TITLE
Cloud ML sdk for python3

### ISSUE THREAD

**Issue by rajhans** [GoogleCloudPlatform/cloudml-samples#17]
Is there any timeline on when do you plan to add support for python3 in cloud ml SDK? It appears many other cloud libraries do support python 3 (like storage), and it will be great to have it for the ML sdk as well.

Thanks!

**Comment by puneith** [comment]
@rajhans Cloud ML SDK is now deprecated effective May 2017. You should use  [tf.Transform](https://github.com/tensorflow/transform) and can checkout [samples](https://github.com/GoogleCloudPlatform/cloudml-samples) under criteo_tft and reddit_tft. You can also checkout the [release notes](https://cloud.google.com/ml-engine/docs/resources/release-notes)
