### ISSUE TITLE
Scikit-learn on ML Engine

### ISSUE THREAD

**Issue by francescoperera** [GoogleCloudPlatform/cloudml-samples#177]
Hi, 
I just noticed that an example of scikit-learn support on ML Engine was posted a few days ago under `sklearn/notebooks/Online Prediction with scikit-learn.ipynb`. This examples show us how  to deploy a scikit-learn model. I noticed that in the body of the `projects.models.versions.create` API call there is a new field called `framework` that allows you to specify what framework model to deploy.  However the ML Engine docs do not show this field ( https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions/create). Am I missing something here ? Is this a new update to the API? How did you find this out ?

A secondary question is that I noticed that scikit-learn model was trained locally in the notebook. Can we leverage ML Engine for training as well ?

**Comment by dizcology** [comment]
@francescoperera Serving scikit-learn and xgboost models is a new feature of Cloud ML Engine.  On [this page](https://cloud.google.com/ml-engine/docs/scikit/getting-predictions#create_a_model_version) you can see some information about the `framework` field.  

In short, `framework` must be "SCIKIT_LEARN" or "XGBOOST".

Training scikit-learn and xgboost model is not currently supported on Cloud ML Engine.

**Comment by thedriftofwords** [comment]
@francescoperera 

The method pages (like [`projects.models.versions.create`](https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions/create)) don't show all the possible parameters. The page for the relevant resource - [`Version`](https://cloud.google.com/ml-engine/reference/rest/v1/projects.models.versions) - shows all the parameters, including `framework`. 

In general, you can find Cloud ML Engine updates in our [release notes](https://cloud.google.com/ml-engine/docs/release-notes).

**Comment by francescoperera** [comment]
@thedriftofwords @dizcology  thanks for the replies. Just wondering what best practices would be to  train scikit learn on GCP ? GCE instances? If so what do you tips on how to build resilient/ production grade training jobs ?

**Comment by thedriftofwords** [comment]
@francescoperera [This tutorial](https://github.com/GoogleCloudPlatform/ml-on-gcp/tree/master/gce/survival-training)might be of interest to you. Although it is a TensorFlow tutorial, and the scikit-learn version is still in progress, it has information about how to build resilient training jobs on GCE instances.
