### ISSUE TITLE
Training and Evaluation Jobs on Google Cloud ML Engine ERROR

### ISSUE THREAD

**Issue by khorsandi2014** [GoogleCloudPlatform/cloudml-samples#179]
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 3.6
- **Exact command to reproduce**: 
gcloud ml-engine jobs submit training `whoami`_object_detection_`date +%s` \
    --runtime-version 1.2 \
    --job-dir=gs://${YOUR_GCS_BUCKET}/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --region us-central1 \
    --config object_detection/samples/cloud/cloud.yml \
    -- \
    --train_dir=gs://${YOUR_GCS_BUCKET}/train \
    --pipeline_config_path=gs://${YOUR_GCS_BUCKET}/data/faster_rcnn_resnet101_pets.config

### Describe the problem
replicating object recognition API
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

### Source code / log
ps-replica-0
Retrying after gsutil exception Command '['gsutil', '-q', 'cp', u'gs://konica2/train/packages/e54cf4013a6b3db25708b644afd60cef025f058ababd32a3806d7d8fe021fadb/object_detection-0.1.tar.gz', u'object_detection-0.1.tar.gz']' returned non-zero exit status 1.

**Comment by dizcology** [comment]
@khorsandi2014 Thank you for reporting the issue.  From the log you provided it appears as if the training job could not access the training package.  Does your bucket have access limitations?

**Comment by khorsandi2014** [comment]
@dizcology Thanks! I did not change settings on my bucket or GC. How can I check if there is access limitations?

**Comment by thedriftofwords** [comment]
@khorsandi2014 If your ML Engine project doesn't have access to your Cloud Storage bucket, see: https://cloud.google.com/ml-engine/docs/tensorflow/working-with-cloud-storage

**Comment by khorsandi2014** [comment]
@thedriftofwords Thanks! Now, I get these errors: 

1- tensorflow 1.2.0 has requirement wheel, but you'll have wheel 0.30.0a0 which is incompatible.

2- Command '['python', '-m', u'object_detection.train', u'--train_dir=gs://object-bucket2/train', u'--pipeline_config_path=gs://object-bucket2/data/faster_rcnn_resnet101_pets.config', '--job-dir', u'gs://object-bucket2/train']' returned non-zero exit status 1

Tensorflow version was 1.5 and I downgraded tensorflow to 1.2. (Mac OS and Python 2.7)

**Comment by mesargent** [comment]
I'm getting the same error, along with 
ps-replica-1
/usr/bin/python: No module named object_detection.train

**Comment by NatLun091238** [comment]
I get similar, but a bit different error. It looks like this.
worker-replica-21
Command '['python', '-m', u'trainer.task', u'--output_dir=gs://the_puth', u'--topk=25', u'--job-dir=/tmp', '--job-dir', u'gs://the_puth']' returned non-zero exit status -9
Any ideas how to solve this??

**Comment by aawgit** [comment]
In my case, I had made a mistake in the path to model.ckpt file. Solved the issue by correcting it. I suggest looking at the earlier entries of the log. It will probably reveal more information on where the culprit is.

**Comment by puneith** [comment]
@khorsandi2014 can you look into solution from @aawgit and see if it works. Feel free to open an SO post and link this issue, if still unsolved. The issue is reported against object recognition API, so belongs on SO.
