### ISSUE TITLE
cloudml-template/README.md points to the wrong links

### ISSUE THREAD

**Issue by iolalla** [GoogleCloudPlatform/cloudml-samples#181]
The links included in cloudml-samples/README.md point to https://github.com/ksalama/cloudml-samples/blob/master/cloudml-template/template/ and should point to https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/cloudml-template/template/ 

This is a Documentation error and happens in every OS, browser, etc.

**Comment by iolalla** [comment]
Here goes the patch I've generated to solve it.

[patch.txt](https://github.com/GoogleCloudPlatform/cloudml-samples/files/1904183/patch.txt)

**Comment by thedriftofwords** [comment]
Thanks for the fix, @iolalla! I wasn't sure how to use your patch.txt, so I made a PR myself - feel free to take a look and verify that it resolves the problem.

**Comment by ksalama** [comment]
@iolalla - I think the issue can be closed now

**Comment by iolalla** [comment]
Both are right. This issue is fixed.
