### ISSUE TITLE
ML Engine Quota Question

### ISSUE THREAD

**Issue by sbsends** [GoogleCloudPlatform/cloudml-samples#183]
Dear ML Engine Team,

Before building an app using the ml-engine I need to know whether the deployed model quota (currently 100) can be significantly increased. 

I have contacted sales, technical support, and filled out the custom quota request form. Alas, I still haven’t received an answer. Can you put me into contact with the right people? Sorry to file a GH issue, but i’ve had no luck with other avenues of communication.

**Comment by sbsends** [comment]
Sorry to tag you. The only reason I am here is because the uncertainty about model quota is massively bottlenecking my project. I appreciate your time/insight.

@broady @amygdala @cdibona @mrry @tswast

**Comment by lluunn** [comment]
Hi, please send an email to cloudml-feedback@google.com.

**Comment by sbsends** [comment]
Thank you @lluunn! Closing.
