### ISSUE TITLE
Hyperparameter tuning training job getting confused with training and eval metrics due to same name

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/cloudml-samples#184]
Hyperparameter tuning training job getting confused with training and eval metrics due to same name. See this [SO](https://stackoverflow.com/questions/49057830/too-many-hyperparameter-tuning-metrics-written-out/49057831#49057831) link which also has guidance on how to fix it.

**Comment by happyhuman** [comment]
@puneith where exactly is the code that needs be fixed? Can you provide the file and/or function name?

**Comment by puneith** [comment]
@happyhuman See this code https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/estimator/trainer/task.py#L43 where you need to add the params as per this code (see rmse in [SO](https://stackoverflow.com/questions/49057830/too-many-hyperparameter-tuning-metrics-written-out/49057831#49057831)) and return another estimator. 

estimator = tf.contrib.estimator.add_metrics(estimator, my_rmse)

**Comment by puneith** [comment]
@happyhuman ping on this issue.

**Comment by nnegrey** [comment]
@happyhuman PTAL to verify if this is still an issue or close this bug, thanks!

**Comment by nnegrey** [comment]
Ping

**Comment by happyhuman** [comment]
Assigning it to @gogasca (it is TensorFlow code).

**Comment by gogasca** [comment]
Will take a look

**Comment by andrewferlitsch** [comment]
@happyhuman is this still a bug or can we close it?

**Comment by andrewferlitsch** [comment]
Will close per conversation with happyhuman:
