### ISSUE TITLE
use built-in xgboost evaluator

### ISSUE THREAD

**Issue by sirtorry** [GoogleCloudPlatform/cloudml-samples#185]
[census xgboost notebook](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/xgboost/notebooks/Online%20Prediction%20with%20XGBoost.ipynb)

**Comment by puneith** [comment]
@sirtorry does this need to be resolved?

**Comment by sirtorry** [comment]
it needs to be worked on. it'll take a few mins but keeps escaping me.

**Comment by sirtorry** [comment]
@happyhuman would you be willing to take this. would be nice if we used xgboost's built-in evaluator rather than what's done here.
