### ISSUE TITLE
Cannot access census data

### ISSUE THREAD

**Issue by sebamlu** [GoogleCloudPlatform/cloudml-samples#194]
Seems to be a problem with the public billing account, i got this problem when trying to download the data:

$ gsutil cp gs://cloudml-public/census/data/* local/data
> Copying gs://cloudml-public/census/data/adult.data.csv...
> bAccessDeniedException: 403  MiB]

Also if I try to navigate to: 
https://storage.cloud.google.com/cloudml-public/testdata/prediction/census.json

got this message:
"The project to be billed is associated with a closed billing account."

**Comment by thedriftofwords** [comment]
@sebamlu Thanks for letting us know! We brought that account back online temporarily while we move the data to a different account. I'm leaving this issue open until that update is complete, as we will be changing the bucket names in the samples and docs accordingly.

**Comment by thedriftofwords** [comment]
#195 has been approved & merged.

**Comment by sirtorry** [comment]
dataset moved to gs://cloud-samples-data/ml-engine/census/data/*
closed issue.
