### ISSUE TITLE
Num_epochs is not used in train_and_evaluate examples

### ISSUE THREAD

**Issue by rasmi** [GoogleCloudPlatform/cloudml-samples#197]
In the census example, [`num_epochs` gives the impression](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/90005b4378dbc03ebeb7e53277ccbe9592292c06/census/estimator/trainer/task.py#L67-L75) that training will stop after that many epochs. This is not the case because [`train_and_evaluate`](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/90005b4378dbc03ebeb7e53277ccbe9592292c06/census/estimator/trainer/task.py#L54) does not respect the OutOfRangeError thrown by [dataset.repeat(num_epochs)](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/90005b4378dbc03ebeb7e53277ccbe9592292c06/census/estimator/trainer/model.py#L286). 

See docs [here](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate):
> Stop condition: In order to support both distributed and non-distributed configuration reliably, the only supported stop condition for model training is train_spec.max_steps. If train_spec.max_steps is None, the model is trained forever. Use with care if model stop condition is different. For example, assume that the model is expected to be trained with one epoch of training data, and the training input_fn is configured to throw OutOfRangeError after going through one epoch, which stops the Estimator.train. For a three-training-worker distributed configuration, each training worker is likely to go through the whole epoch independently. So, the model will be trained with three epochs of training data instead of one epoch.

**Comment by gogasca** [comment]
This is more a TF issue than CMLE problem. Closing for now
