### ISSUE TITLE
"Unable to get the Filesystem .." in flowers/sample.sh with cloudshell

### ISSUE THREAD

**Issue by yuvalaviel** [GoogleCloudPlatform/cloudml-samples#198]
### system
- OS Platform and Distribution : cloudshell
- TensorFlow version 1.8.0
- Python version 2.7.13
- Exact command to reproduce:
```
cd flowers
sudo pip install --upgrade pip apache_beam pillow tensorflow
declare GOOGLE_APPLICATION_CREDENTIALS="~/agri-vision-service.json"
./sample.sh
```

### The problem:
When running ./sample.sh, I get (for the preprocess.py command):
ValueError: Unable to get the Filesystem for path gs://cloud-ml-data/img/flower_photos/eval_set.csv

I wouldn't get this error before. Its a new thing.

 ### attempts
```
~/flowers$ gsutil ls -l gs://cloud-ml-data/img/flower_photos/eval_set.csv
     29957  2016-11-15T01:16:45Z  gs://cloud-ml-data/img/flower_photos/eval_set.csv
TOTAL: 1 objects, 29957 bytes (29.25 KiB)
```

==> so the file exists.

```
pip uninstall tensorflow
pip install tensorflow==1.7.0
```
==> same error

Running from another account seems to pass this stage (its another guy)
==> permission/key issue??

### Source code / logs
yuval_aviel@growth-stage:~$ gcloud config set project agri-vision
Updated property [core/project].
yuval_aviel@agri-vision:~$ GOOGLE_APPLICATION_CREDENTIALS="~/agri-vision-service.json"
yuval_aviel@agri-vision:~$ declare GOOGLE_APPLICATION_CREDENTIALS="~/agri-vision-service.json"
yuval_aviel@agri-vision:~$ sudo pip install --upgrade pip apache_beam pillow tensorflow #==1.7.0
********************************************************************************
You are running pip as root. Note that that your Cloud Shell machine is ephemeral
and no system-wide change will persist beyond session end.
To be whitelisted for an alpha feature that enables you to permanently customize
your Cloud Shell environment, email cloud-shell-custom-environments-alpha@googlegroups.com
and request to join the Cloud Shell custom environments alpha.

Once you are whitelisted, we will respond with instructions on how to use the feature.
********************************************************************************
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg (10.0.1)
Requirement already up-to-date: apache_beam in /usr/local/lib/python2.7/dist-packages (2.4.0)
Requirement already up-to-date: pillow in /usr/local/lib/python2.7/dist-packages (5.1.0)
Requirement already up-to-date: tensorflow in /usr/local/lib/python2.7/dist-packages (1.8.0)
Requirement not upgraded as not directly required: futures<4.0.0,>=3.1.1 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (3.2.0)
Requirement not upgraded as not directly required: dill==0.2.6 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (0.2.6)
Requirement not upgraded as not directly required: protobuf<4,>=3.5.0.post1 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (3.5.2.post1)
Requirement not upgraded as not directly required: six<1.12,>=1.9 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (1.11.0)
Requirement not upgraded as not directly required: oauth2client<5,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (4.1.2)
Requirement not upgraded as not directly required: grpcio<2,>=1.0 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (1.12.0)
Requirement not upgraded as not directly required: typing<3.7.0,>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (3.6.4)
Requirement not upgraded as not directly required: mock<3.0.0,>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (2.0.0)
Requirement not upgraded as not directly required: pyyaml<4.0.0,>=3.12 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (3.12)
Requirement not upgraded as not directly required: pyvcf<0.7.0,>=0.6.8 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (0.6.8)
Requirement not upgraded as not directly required: hdfs<3.0.0,>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (2.1.0)
Requirement not upgraded as not directly required: avro<2.0.0,>=1.8.1 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (1.8.2)
Requirement not upgraded as not directly required: httplib2<0.10,>=0.8 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (0.9.2)
Requirement not upgraded as not directly required: crcmod<2.0,>=1.7 in /usr/local/lib/python2.7/dist-packages (from apache_beam) (1.7)
Requirement not upgraded as not directly required: enum34>=1.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.1.6)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.14.3)
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.1.0)
Requirement not upgraded as not directly required: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.0.post1)
Requirement not upgraded as not directly required: absl-py>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (0.2.1)
Requirement not upgraded as not directly required: wheel in /usr/local/lib/python2.7/dist-packages (from tensorflow) (0.31.1)
Requirement not upgraded as not directly required: tensorboard<1.9.0,>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.8.0)
Requirement not upgraded as not directly required: gast>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (0.2.0)
Requirement not upgraded as not directly required: astor>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (0.6.2)
Requirement not upgraded as not directly required: setuptools in /usr/lib/python2.7/dist-packages (from protobuf<4,>=3.5.0.post1->apache_beam) (33.1.1)
Requirement not upgraded as not directly required: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client<5,>=2.0.1->apache_beam) (3.4.2)
Requirement not upgraded as not directly required: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client<5,>=2.0.1->apache_beam) (0.2.1)
Requirement not upgraded as not directly required: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client<5,>=2.0.1->apache_beam) (0.4.2)
Requirement not upgraded as not directly required: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock<3.0.0,>=1.0.1->apache_beam) (1.0.2)
Requirement not upgraded as not directly required: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock<3.0.0,>=1.0.1->apache_beam) (4.0.3)
Requirement not upgraded as not directly required: requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from hdfs<3.0.0,>=2.1.0->apache_beam) (2.18.4)
Requirement not upgraded as not directly required: docopt in /usr/local/lib/python2.7/dist-packages (from hdfs<3.0.0,>=2.1.0->apache_beam) (0.6.2)
Requirement not upgraded as not directly required: bleach==1.5.0 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (1.5.0)
Requirement not upgraded as not directly required: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (0.9999999)
Requirement not upgraded as not directly required: markdown>=2.6.8 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (2.6.11)
Requirement not upgraded as not directly required: werkzeug>=0.11.10 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow) (0.14.1)
Requirement not upgraded as not directly required: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->hdfs<3.0.0,>=2.1.0->apache_beam) (1.22)
Requirement not upgraded as not directly required: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->hdfs<3.0.0,>=2.1.0->apache_beam) (2.6)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->hdfs<3.0.0,>=2.1.0->apache_beam) (3.0.4)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.7.0->hdfs<3.0.0,>=2.1.0->apache_beam) (2018.4.16)
google-api-core 1.1.2 has requirement setuptools>=34.0.0, but you'll have setuptools 33.1.1 which is incompatible.
yuval_aviel@agri-vision:~$ cd flowers
yuval_aviel@agri-vision:~/flowers$ ./sample.sh

Using job id:  flowers_yuval_aviel_20180529_101754

# Takes about 30 mins to preprocess everything.  We serialize the two
# preprocess.py synchronous calls just for shell scripting ease; you could use
# --runner DataflowRunner to run them asynchronously.  Typically,
# the total worker time is higher when running on Cloud instead of your local
# machine due to increased network traffic and the use of more cost efficient
# CPU's.  Check progress here: https://console.cloud.google.com/dataflow
python trainer/preprocess.py \
  --input_dict "$DICT_FILE" \
  --input_path "gs://cloud-ml-data/img/flower_photos/eval_set.csv" \
  --output_path "${GCS_PATH}/preproc/eval" \
  --cloud
Traceback (most recent call last):
  File "trainer/preprocess.py", line 490, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 486, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 394, in run
    configure_pipeline(p, in_args)
  File "trainer/preprocess.py", line 368, in configure_pipeline
    opt.input_path, strip_trailing_newlines=True)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/textio.py", line 522, in __init__
    skip_header_lines=skip_header_lines)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/textio.py", line 117, in __init__
    validate=validate)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filebasedsource.py", line 118, in __init__
    self._validate()
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/options/value_provider.py", line 124, in _f
    return fnc(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filebasedsource.py", line 175, in _validate
    match_result = FileSystems.match([pattern], limits=[1])[0]
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filesystems.py", line 153, in match
    filesystem = FileSystems.get_filesystem(patterns[0])
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filesystems.py", line 84, in get_filesystem
    raise ValueError('Unable to get the Filesystem for path %s' % path)
ValueError: Unable to get the Filesystem for path gs://cloud-ml-data/img/flower_photos/eval_set.csv
 (1.22)
yuval_aviel@agri-vision:~/flowers$ pip freeze |grep tensorflow
tensorflow==1.8.0
yuval_aviel@agri-vision:~/flowers$ pip freeze |grep apache-beam
apache-beam==2.4.0
yuval_aviel@agri-vision:~/flowers$ python --version
Python 2.7.13
yuval_aviel@agri-vision:~/flowers$ ./sample.sh ValueError: Unable to get the Filesystem for path gs://cloud-ml-data/img/flower_photos/eval_set.csv^C
yuval_aviel@agri-vision:~/flowers$ gsutil ls -l gs://cloud-ml-data/img/flower_photos/eval_set.csv
     29957  2016-11-15T01:16:45Z  gs://cloud-ml-data/img/flower_photos/eval_set.csv
TOTAL: 1 objects, 29957 bytes (29.25 KiB)
yuval_aviel@agri-vision:~/flowers$

**Comment by happyhuman** [comment]
Thanks for reporting the issue. I am looking into it and I will get back to you soon.

**Comment by happyhuman** [comment]
Can you try to install the required libraries, using the `requirements.txt` in `flowers` directory, using this command: `pip install -r requirements.txt`?

**Comment by yuvalaviel** [comment]
Thank you @happyhuman , indeed I missed the version part of the requirements.txt ..

Anyhow, now that I do (you forgot the sudo):
    ```sudo pip install -r requriements.txt```
I get 

```
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '--download', '/tmp/tmpIYnsGL', 'apache-beam==0.6.0', '--no-binary', ':all:', '--no-deps']' returned non-zero 
exit status 2
```

**The error is because there is no option '--download' in pip.
Does the apache-beam really tries to re-install itself??**

### log
```
Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to agri-vision.
Use “gcloud config set project” to change to a different project.
yuval_aviel@agri-vision:~$ cd ~/flowers
yuval_aviel@agri-vision:~/flowers$ sudo pip install -r requirements.txt
********************************************************************************
You are running pip as root. Note that that your Cloud Shell machine is ephemeral
and no system-wide change will persist beyond session end.
To be whitelisted for an alpha feature that enables you to permanently customize
your Cloud Shell environment, email cloud-shell-custom-environments-alpha@googlegroups.com
and request to join the Cloud Shell custom environments alpha.
Requirement already satisfied: mock<3.0.0,>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (2.0.0)

Once you are whitelisted, we will respond with instructions on how to use the feature.
********************************************************************************
Requirement already satisfied: apache-beam[gcp]==0.6.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pillow==4.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: tensorflow==1.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: dill==0.2.6 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.2.6)
Requirement already satisfied: protobuf==3.2.0 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: avro<2.0.0,>=1.7.7 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: mock<3.0.0,>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: oauth2client<4.0.0,>=2.0.1 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: httplib2<0.10,>=0.8 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.9.2)
Requirement already satisfied: crcmod<2.0,>=1.7 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.7)
Requirement already satisfied: pyyaml<4.0.0,>=3.10 in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (3.12)
Requirement already satisfied: google-apitools<1.0.0,>=0.5.6; extra == "gcp" in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.5.23)
Requirement already satisfied: proto-google-cloud-datastore-v1==0.90.0; extra == "gcp" in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.90.0)
Requirement already satisfied: googledatastore==7.0.0; extra == "gcp" in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (7.0.0)
Requirement already satisfied: google-cloud-bigquery<0.23,>=0.22.1; extra == "gcp" in /usr/local/lib/python2.7/dist-packages (from apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.22.1)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from pillow==4.0.0->-r requirements.txt (line 2)) (0.45.1)
Requirement already satisfied: tensorflow-tensorboard<0.5.0,>=0.4.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (1.14.3)
Requirement already satisfied: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (1.0.post1)
Requirement already satisfied: wheel in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (0.31.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (1.11.0)
Requirement already satisfied: enum34>=1.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.4.1->-r requirements.txt (line 3)) (1.1.6)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.2.0->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (33.1.1)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock<3.0.0,>=1.0.1->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock<3.0.0,>=1.0.1->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (4.0.3)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client<4.0.0,>=2.0.1->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client<4.0.0,>=2.0.1->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client<4.0.0,>=2.0.1->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: fasteners>=0.14 in /usr/local/lib/python2.7/dist-packages (from google-apitools<1.0.0,>=0.5.6; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.14.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from proto-google-cloud-datastore-v1==0.90.0; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: google-cloud-core<0.23dev,>=0.22.1 in /usr/local/lib/python2.7/dist-packages (from google-cloud-bigquery<0.23,>=0.22.1; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.22.1)
Requirement already satisfied: bleach==1.5.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1->-r requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1->-r requirements.txt (line 3)) (2.6.11)
Requirement already satisfied: futures>=3.1.1; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1->-r requirements.txt (line 3)) (0.9999999)
Requirement already satisfied: werkzeug>=0.11.10 in /usr/local/lib/python2.7/dist-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1->-r requirements.txt (line 3)) (0.14.1)
Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python2.7/dist-packages (from fasteners>=0.14->google-apitools<1.0.0,>=0.5.6; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.5)
Requirement already satisfied: google-auth<2.0.0dev,>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-bigquery<0.23,>=0.22.1; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (1.4.1)
Requirement already satisfied: google-auth-httplib2 in /usr/local/lib/python2.7/dist-packages (from google-cloud-core<0.23dev,>=0.22.1->google-cloud-bigquery<0.23,>=0.22.1; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (0.0.3)
Requirement already satisfied: cachetools>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.23dev,>=0.22.1->google-cloud-bigquery<0.23,>=0.22.1; extra == "gcp"->apache-beam[gcp]==0.6.0->-r requirements.txt (line 1)) (2.1.0)
google-cloud-storage 1.10.0 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.22.1 which is incompatible.
google-api-core 1.1.2 has requirement setuptools>=34.0.0, but you'll have setuptools 33.1.1 which is incompatible.
google-cloud-translate 1.3.1 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.22.1 which is incompatible.
google-cloud-logging 1.6.0 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.22.1 which is incompatible.
tensorboard 1.8.0 has requirement protobuf>=3.4.0, but you'll have protobuf 3.2.0 which is incompatible.
tensorflow 1.4.1 has requirement protobuf>=3.3.0, but you'll have protobuf 3.2.0 which is incompatible.
google-cloud-datastore 1.6.0 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.22.1 which is incompatible.
google-cloud-spanner 1.3.0 has requirement google-cloud-core<0.29dev,>=0.28.0, but you'll have google-cloud-core 0.22.1 which is incompatible.
tensorflow-tensorboard 0.4.0 has requirement protobuf>=3.4.0, but you'll have protobuf 3.2.0 which is incompatible.
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$ GOOGLE_APPLICATION_CREDENTIALS="~/agri-vision-service.json"
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$ declare -r BUCKET_NAME="gs://agri-vision-ml"
yuval_aviel@agri-vision:~/flowers$  declare -r REGION="us-central1"
yuval_aviel@agri-vision:~/flowers$  declare -r PROJECT_ID=$(gcloud config list project --format "value(core.project)")
yuval_aviel@agri-vision:~/flowers$  declare -r JOB_NAME="flowers_${USER}_$(date +%Y%m%d_%H%M%S)"
yuval_aviel@agri-vision:~/flowers$  declare -r GCS_PATH="${BUCKET_NAME}/${USER}/${JOB_NAME}"
yuval_aviel@agri-vision:~/flowers$  declare -r DICT_FILE=gs://cloud-ml-data/img/flower_photos/dict.txt
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$  declare -r MODEL_NAME=flowers
yuval_aviel@agri-vision:~/flowers$  declare -r VERSION_NAME=v1
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$  echo

yuval_aviel@agri-vision:~/flowers$  echo "Using job id: " $JOB_NAME
Using job id:  flowers_yuval_aviel_20180529_221835
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$  gsutil cp /dev/null "$GCS_PATH/preproc/eval/"
Copying file:///dev/null [Content-Type=application/octet-stream]...
/ [1 files][    0.0 B/    0.0 B]
Operation completed over 1 objects.
yuval_aviel@agri-vision:~/flowers$  gsutil cp /dev/null "$GCS_PATH/preproc/train/"
Copying file:///dev/null [Content-Type=application/octet-stream]...
/ [1 files][    0.0 B/    0.0 B]
Operation completed over 1 objects.
yuval_aviel@agri-vision:~/flowers$
yuval_aviel@agri-vision:~/flowers$  declare srcEval="gs://cloud-ml-data/img/flower_photos/eval_set.csv" #  gs://cloud-ml-data/img/flower_photos/eval_set.csv
yuval_aviel@agri-vision:~/flowers$ python trainer/preprocess.py     --input_dict "$DICT_FILE"     --input_path "$srcEval" --output_path "${GCS_PATH}/preproc/eval"  --cloud
/usr/local/lib/python2.7/dist-packages/apache_beam/coders/typecoders.py:132: UserWarning: Using fallback coder for typehint: Any.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
Usage:
  /usr/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/bin/python -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python -m pip install [options] [-e] <local project path> ...
  /usr/bin/python -m pip install [options] <archive url/path> ...

no such option: --download
Traceback (most recent call last):
  File "trainer/preprocess.py", line 490, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 486, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 394, in run
    configure_pipeline(p, in_args)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 170, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 163, in run
    return self.runner.run(self)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 175, in run
    self.dataflow_client.create_job(self.job), self)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/utils/retry.py", line 174, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 411, in create_job
    self.create_job_description(job)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 432, in create_job_description
    job.options, file_copy=self._gcs_file_copy)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/internal/dependency.py", line 362, in stage_job_resources
    _stage_beam_sdk_tarball(sdk_remote_location, staged_path, temp_dir)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/internal/dependency.py", line 447, in _stage_beam_sdk_tarball
    _dependency_file_copy(_download_pypi_sdk_package(temp_dir), staged_path)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/internal/dependency.py", line 510, in _download_pypi_sdk_package
    processes.check_call(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/utils/processes.py", line 40, in check_call
    return subprocess.check_call(*args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '--download', '/tmp/tmp4vkrkt', 'apache-beam==0.6.0', '--no-binary', ':all:', '--no-deps']' returned non-zero exit status 2
yuval_aviel@agri-vision:~/flowers$
```

**Comment by yuvalaviel** [comment]
OK, I managed to make it work.
* I noticed that dataflow API was not enabled (isn't there a script to check this?)

**Comment by happyhuman** [comment]
Oh good. I am glad to hear it worked out.
I am not sure whether there is a script to tell if the dataflow API is enabled. I will try to find out.

**Comment by yuvalaviel** [comment]
Hi @happyhuman , 

not this edit above:
* The apache-beam version is 2.3.0, not 0.6.0 as in the requirements.txt

Other users might have similar issue ...
