### ISSUE TITLE
Updating movielens TF version

### ISSUE THREAD

**Issue by daltonj** [GoogleCloudPlatform/cloudml-samples#201]
The movielens example is quite out of date. According to setup.py the version currently being used is:

TENSORFLOW='tensorflow==1.3.0'
TENSORFLOW_TRANSFORM='tensorflow-transform==0.3'

Are there plans to update the example to a more recent release?  We are now on transform version 0.6.0. 

I tried updating the versions, but the code appears to be using deprecated / outdated APIs that are no longer supported.

**Comment by happyhuman** [comment]
Thanks for reporting this. We will certainly look into the issue. Were you able to modify and update the versions and the code and run it?

**Comment by daltonj** [comment]
I was able to run it with great difficulty. I received many warnings that many of the tensorflow functions are removed.

WARNING:tensorflow:From .../cloudml-samples/movielens/preproc/movielens.py:256: string_to_index_table_from_file (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_file`.
WARNING:tensorflow:From .../code/cloudml-samples/movielens/cmle-env/local/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py:337: string_to_index_table_from_file (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.

These have been removed for over a year now.  As a result, I can't upgrade this project to newer versions of tensorflow without these breaking.  It requires both a tensorflow and a beam update.

**Comment by nnegrey** [comment]
Hi! Hope I understand correctly that even with all the issues you were able to get it running?

We are hoping/planning to get these updated, but I don't have an ETA on when that will happen.

We do love community contributions and if you want to push your solution, that would be awesome!
Check out our guide [here](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/CONTRIBUTING.md)

**Comment by lesterlitch** [comment]
It would be really great to update these - the workflows are significantly different from many data science python workflows (pandas, keras, jupyter etc.), so could really use some worked examples to dev off.
