### ISSUE TITLE
Flowers Sample: python -m tensorflow.tensorboard --logdir=$OUTPUT_PATH deprecated

### ISSUE THREAD

**Issue by willbattel** [GoogleCloudPlatform/cloudml-samples#215]
It seems the docs need to be updated to use the new tensorboard command. https://cloud.google.com/ml-engine/docs/tensorflow/flowers-tutorial#monitor_training_progress

`python -m tensorflow.tensorboard --logdir=$OUTPUT_PATH` should be replaced with `tensorboard --logdir=$OUTPUT_PATH` according to Tensorflow https://github.com/tensorflow/tensorflow/issues/10959#issuecomment-323440512

**Comment by puneith** [comment]
@thedriftofwords can we open docs bug and close this issue.

**Comment by gogasca** [comment]
Created fix internally. Closing Public github issue
