### ISSUE TITLE
Criteo example - update to TF Estimators?

### ISSUE THREAD

**Issue by awan-10** [GoogleCloudPlatform/cloudml-samples#216]
This is not a bug report but I have no other way of asking this question. 

Do you guys plan to update the Criteo example with the new TF Estimator interface? 

I would like to use the latest version of TensorFlow for the Criteo example in the Cloud and it shows a lot of warnings with the old/deprecated tf.contrib.learn interace.

**Comment by puneith** [comment]
@awan-10 No plans right now but are you open to taking a stab at it and we will happily provide guidance. You can use the custom estimator Census as an example.

**Comment by awan-10** [comment]
@puneith - Thanks for the feedback. I will be working on it two weeks from now. If I run into problems, should I post in this thread or create a new issue? 

Also a few quick questions are about Sparse columns and DNN classifiers. I see the following:

```
DNNClassifier and DNNRegressor: Only accept dense columns. Other column types must be wrapped in either an indicator_column or embedding_column
```

Can you point me to any examples, if you are aware of, to convert the spare columns/crossed columns to the new tf.feature_column API that is suitable for use with tf.estimator.DNNClassifer?

**Comment by puneith** [comment]
@awan-10 Checkout this code https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/cloudml-template/examples/census-classification/trainer/featurizer.py. @ksalama for FYI and any follow-up questions.

**Comment by puneith** [comment]
Closing this as per above comment.
