### ISSUE TITLE
check_environment.py  WARNING: Couldn't find python-snappy.

### ISSUE THREAD

**Issue by mchirico** [GoogleCloudPlatform/cloudml-samples#22]
I had to perform the following commands to get python-snappy installed.  

    sudo apt-get install libsnappy-dev
    sudo pip install python-snappy

The Cloud shell appears to be missing this library and package.  It might be helpful to include a note in the instructions.

**Comment by elmer-garduno** [comment]
Thanks for the feedback. We will look into getting this warning removed from the setup script.
