### ISSUE TITLE
No module object_detection.train

### ISSUE THREAD

**Issue by mesargent** [GoogleCloudPlatform/cloudml-samples#223]
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux 17.04
- **TensorFlow version (use command below)**:
1.9.0
- **Python version**:
2.7.13
- **Exact command to reproduce**:
```
gcloud ml-engine jobs submit training object_detection_$(date +%Y%m%d_%H%M%S)  \
    --job-dir="gs://mybucketl/train" \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --region us-central1 \
    --config /home/me/Desktop/die_detection/config.yml \
    -- \
    --train_dir="gs://mybucketl/train" \
    --pipeline_config_path="gs://mybucketl/data/pipeline_cloud.config"
```

- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
the sample code, and whether it occurred locally or on the server (CloudML Engine,
Google Dataflow)
Tried following this sample, but with my own data: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

Works fine locally. Running on CloudML Engine, I get a non-0 exit status. From the logs it seems object_detection.train cannot be found.

### Source code / logs
```
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
E  The replica ps 0 exited with a non-zero status of 1. Termination reason: Error. To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=730275006403&resource=ml_job%2Fjob_id%2Fobject_detection_20180725_090524&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22object_detection_20180725_090524%22 
  undefined
E  ps-replica-0 Command '['python', '-m', u'object_detection.train', u'--train_dir=gs://tfodtut-ml/train', u'--pipeline_config_path=gs://tfodtut-ml/data/pipeline_cloud.config', '--job-dir', u'gs://tfodtut-ml/train']' returned non-zero exit status 1 ps-replica-0 
  undefined
E  ps-replica-0 /usr/bin/python: No module named object_detection.train ps-replica-0 
  undefined
```

**Comment by mesargent** [comment]
Will try SO first to see if it's really a bug.

**Comment by lebuckle** [comment]
I'm having the same issue, did you get it fixed?
