### ISSUE TITLE
Cloud ML | Object detection model deploying error: op type not registered nonmaxsuppressionv3

### ISSUE THREAD

**Issue by g-hrafiq** [GoogleCloudPlatform/cloudml-samples#224]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Unix on GCP
- **TensorFlow version**: 1.9 on GCP
- **Python version**: 2.7.13
- **Exact command to reproduce**: gcloud ml-engine versions create 
- **Tensorflow Transform environment (if applicable, see below)**: NA

### Describe the problem
CloudML issue: While trying to deploy a CMLE custom trained object detection( **faster_rcnn_resnet101_coco_11_06_2017** or **faster_rcnn_resnet101_coco_2018_01_28** ) model on TF 1.8 runtime on CMLE serving, encountered an error: **Create Version failed. Bad model detected with error: "Failed to load model: Loading servable: {name: default version: 1} failed: Not found: Op type not registered 'NonMaxSuppressionV3' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process.\n\n (Error code: 0)"**

Exact model export command:

```
gcloud ml-engine versions create v1 \
--model visual_insp \
--origin gs://<bucket>/model/saved_model \
--runtime-version 1.8
```

Command for training( Job ran successfully ) till the end: 

    gcloud ml-engine jobs submit training  'vi_job_28july_16' \
    --job-dir=gs://<bucket>/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz \
    --module-name object_detection.model_main \
    --runtime-version 1.8 \
    --region us-central1 \
    --config object_detection/samples/cloud/cloud.yml \
    -- \
    --model_dir=gs://<bucket>/train \
    --pipeline_config_path=gs://<bucket>/data/gcp_pipeline.config

Cloud.yml file used for training:

```
trainingInput:
  runtimeVersion: "1.8"
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerCount: 5
  workerType: standard_gpu
  parameterServerCount: 3
  parameterServerType: standard
```

**Comment by g-hrafiq** [comment]
Creating on Tensorflow's GIT https://github.com/tensorflow/models/issues/4928

**Comment by g-hrafiq** [comment]
Keeping incident open for any of the teams to work on.

**Comment by g-hrafiq** [comment]
Solved myself, I was using TF 1.9 on GCP. Had to downgrade to TF 1.8 and then run export_inference_graph.py again.

After that I was able to host on CMLE serving.

**Comment by g-hrafiq** [comment]
Yes its simple, you have to first downgrade TF on Cloud shell to 1.8 by using `pip install tensorflow==1.8.0`

Then use the normal cloud ML engine training command on Cloud shell.

**Comment by JohnSDevs** [comment]
Ok. 
I Managed to train on 1.8 but still the same error. 
Gotta ask, are you running everything from inside the cloud shell?

I tried to do that but running export_inference_graph.py gave me
“Killed” error. Not enough memmory for those tasks. 

Could you explain more in detail your workflow and what version of Object detection API you used(what release) and could you share your pipeline.config?

**Comment by g-hrafiq** [comment]
Can you launch the Cloud Shell in Boost mode ? I had similar kind of errors while running export inference code. I was able to solve this by running shell on Boost mode.

This option appears in the cloud shell console top right "gear" icon. https://cloud.google.com/shell/docs/features#boost_mode

**Comment by JohnSDevs** [comment]
Thx! It worked. I did the export of my old models trained in 1.9 and run it on the boosted shell with TF 1.8.

Have to find my bug cos i have done a couple of reinstalls on my macbook and i have done the same workflow.
