### ISSUE TITLE
The job doesn't finish but hangs with a message "Skip the current checkpoint eval due to throttle secs (600 secs)."

### ISSUE THREAD

**Issue by volodymyrd** [GoogleCloudPlatform/cloudml-samples#228]
### System information
GCP console
tensorflow==1.9.0

### Describe the problem
I run  a local training job in distributed mode according to the [getting started guid](https://cloud.google.com/ml-engine/docs/tensorflow/getting-started-training-prediction) in the CGP console, and job doesn't finish but stuck with the message  "INFO:tensorflow:Skip the current checkpoint eval due to throttle secs (600 secs)."
The same situation I've experienced when submitted the job to the cloud.
I've changed nothing in the source code, one difference is the GCP console uses tensorflow 1.9.0.

Thanks
Volodymyr

**Comment by happyhuman** [comment]
Thank you for your message and raising the issue. Can you please tell me which one of the sample codes in this repo were you trying to run?

**Comment by happyhuman** [comment]
Thanks for the clarification. Please allow me a day or two to look into it. In the meantime, if you happen to have any update or progress, please leave a comment here.

**Comment by happyhuman** [comment]
I tried to reproduce this issue, but I was unable to reproduce it. Can you tell me more about the steps you took to reproduce it? The more details the better. Thanks.

**Comment by volodymyrd** [comment]
I've tried it once again and it works as expected. Sorry for trouble, I close the issue, thanks a lot!

**Comment by volodymyrd** [comment]
I see the [changes](https://github.com/GoogleCloudPlatform/cloudml-samples/commit/987792c1f8a12c0c82c9bc835a3b6ffaf42c617b) was 4 days ago probably it fixed the problem, because with the old repo I can reproduce the issue.
