### ISSUE TITLE
Include Tensorboard in Trainer Package Template

### ISSUE THREAD

**Issue by mr-bjerre** [GoogleCloudPlatform/cloudml-samples#231]
In [Trainer Package Template](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/cloudml-template) it would be valuable if it was optimized for running tensorboard as well when running truly locally.

If I run the training now and then run Tensorboard pointing to the job dir then I don't see the full output. The following snapshot is from a run on [census](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/cloudml-template/examples/census-classification).

![image](https://user-images.githubusercontent.com/16841792/44256356-2db45b00-a209-11e8-8c3e-427c6d270648.png)

**Comment by nnegrey** [comment]
Hi! Thanks for the feedback and I'll see what I can do to make that happen.

**Comment by gogasca** [comment]
We have added a new template that should make it happen, I tested and it works fine

**Comment by realtybaron** [comment]
@gogasca which template was added specifically?
