### ISSUE TITLE
Census Sample - estimator/trainer/model.py

### ISSUE THREAD

**Issue by genesisfatum** [GoogleCloudPlatform/cloudml-samples#237]
**Describe the bug**
It seems to me that for this [model](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/estimator/trainer/model.py), the "example_serving_input_fn" does not work because the "feature_scalars" variable is not used. Instead the "features" variable is used and this is not defined. 

**What sample is this bug related to?**
Cloud Sample - Census (estimator)

**Source code / logs**
NA

**To Reproduce**

1. Go to [task.py
](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/estimator/trainer/task.py)
2. Change default parameter from JSON to EXAMPLE for the "export-format" argument
3. Train model locally

**Expected behavior**
The model training should be successful and at prediction time, the serving function should work.

**System Information**
- Linux Ubuntu 16.04
- Tensorflow 1.10
- Python 3.6

**Comment by sirtorry** [comment]
fix merged. closing issue.
