### ISSUE TITLE
Wrong title for Figure 2 in the tutorial

### ISSUE THREAD

**Issue by RodenLuo** [GoogleCloudPlatform/cloudml-samples#24]
I guess the writer forgot to change the title for Figure 2 In [this tutorial](https://cloud.google.com/blog/big-data/2016/12/how-to-classify-images-with-tensorflow-using-google-cloud-machine-learning-and-cloud-dataflow).

**Comment by puneith** [comment]
You mean the loss and accuracy graph? What about its title?

**Comment by RodenLuo** [comment]
It uses "Figure 2: We retrain only a small section of the original inception graph." But as you said, it is loss and accuracy. "We retrain only a small section of the original inception graph." This sentence is for Figure1.

(Nothing really matters, though. People will understand. )

**Comment by puneith** [comment]
@RodenLuo Fixed!
