### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by Ankitagupta3988** [GoogleCloudPlatform/cloudml-samples#243]
Getting below error on pre-processing of evaluation data.

Command that I am running - 

    python trainer/preprocess.py \
        --input_dict "$DICT_FILE" \
        --input_path "gs://cloud-ml-data/img/flower_photos/eval_set.csv" \
        --output_path "${GCS_PATH}/preproc/eval" \
        --cloud

**Error**

     File "trainer/preprocess.py", line 490, in <module>main(sys.argv[1:])
      File "trainer/preprocess.py", line 486, in main run(arg_dict)
      File "trainer/preprocess.py", line 393, in run with beam.Pipeline(options=pipeline_options) as p:
      File "/home/ankitagupta/.local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 131, in __init__
        'Pipeline has validations errors: \n' + '\n'.join(errors))
    ValueError: Pipeline has validations errors:
    Invalid GCS bucket (gs:// ml-flowers-216007/ankitagupta/flowers_ankitagupta_20180910_144047/preproc/temp), given for the option: temp_location. See https://developers.google.com/storage/docs/bucketnaming for more details.

**Comment by dizcology** [comment]
Hi @Ankitagupta3988:  There seems to be a space between `gs://` and `ml-flowers-216007/...` in the GCS path.

**Comment by lokeshsoni** [comment]
![image](https://user-images.githubusercontent.com/27202916/46418557-a6379280-c749-11e8-9782-f5a0133ca855.png)

Following the code as it is, is giving error on the Dataflow console 
Please re-check the code as its updated months back!
Not able to follow the same

**Comment by gogasca** [comment]
@lokeshsoni Looks like the error is related to your Notebook configuration. Flowers code has been updated to latest supported CMLE version TF 1.10. Looks like you error is referring to: https://stackoverflow.com/questions/45179915/importerror-no-module-named-ipython
