### ISSUE TITLE
Getting error in training custom data

### ISSUE THREAD

**Issue by Ankitagupta3988** [GoogleCloudPlatform/cloudml-samples#249]
Hi,

I am using my own Data set of animals.
I have been able preprocess it successfully.
But i am getting below error in job execution.

ERROR-
```
 Error reported to Coordinator: <type 'exceptions.IndexError'>, list index out of range
 Error reported to Coordinator: <type 'exceptions.IndexError'>, list index out of range
 Traceback (most recent call last):
   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
     exec code in run_globals
   File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 542, in <module>
     tf.app.run()
   File "/root/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
   File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 305, in main
     run(model, argv)
   File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 436, in run
     dispatch(args, model, cl
```

**Comment by gogasca** [comment]
@Ankitagupta3988 thanks for reporting the issue, 
Few questions,

What model are you using?
What problem are you trying to solve?
Can you share the command you are running when you get the error?
Also this:

- OS
- python -V
- pip freeze

**Comment by Ankitagupta3988** [comment]
I am using flower dataset but have replaced it with my custom images.
Command - 
gcloud ml-engine jobs submit training "$JOB_ID" \
  --stream-logs \
  --module-name trainer.task \
  --package-path trainer \
  --staging-bucket "$BUCKET" \
  --region us-central1 \
  --runtime-version=1.4 \
  -- \
  --output_path "${GCS_PATH}/training" \
  --eval_data_paths "${GCS_PATH}/preproc/eval*" \
  --train_data_paths "${GCS_PATH}/preproc/train*"

this is the command to train the job.
OS - windows on host env.
Python - 2.7.13

pip freeze - 
absl-py==0.4.1
apache-beam==2.5.0
astor==0.7.1
avro==1.8.2
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
bleach==1.5.0
cachetools==2.1.0
certifi==2018.8.24
chardet==3.0.4
crcmod==1.7
decorator==4.3.0
dill==0.2.6
docopt==0.6.2
enum34==1.1.6
fasteners==0.14.1
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.2.0
gapic-google-cloud-pubsub-v1==0.15.4
gast==0.2.0
google-api-core==1.4.0
google-api-python-client==1.7.4
google-apitools==0.5.20
google-auth==1.5.1
google-auth-httplib2==0.0.3
google-cloud-automl==0.1.1
google-cloud-bigquery==0.25.0
google-cloud-core==0.25.0
google-cloud-datastore==1.7.0
google-cloud-language==1.0.2
google-cloud-logging==1.7.0
google-cloud-pubsub==0.26.0
google-cloud-spanner==1.5.0
google-cloud-storage==1.11.0
google-cloud-translate==1.3.1
google-cloud-videointelligence==1.3.0
google-cloud-vision==0.34.0
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
googledatastore==7.0.1
grpc-google-iam-v1==0.11.4
grpcio==1.15.0
hdfs==2.1.0
html5lib==0.9999999
httplib2==0.9.2
idna==2.7
ipaddr==2.2.0
ipython==5.8.0
ipython-genutils==0.2.0
jsonschema==2.6.0
Markdown==2.6.11
meld3==1.0.2
mercurial==4.0
mock==2.0.0
monotonic==1.5
numpy==1.14.5
oauth2==1.9.0.post1
oauth2client==3.0.0
olefile==0.46
pathlib2==2.3.2
pbr==4.2.0
pexpect==4.6.0
pickleshare==0.7.4
Pillow==4.0.0
ply==3.8
prompt-toolkit==1.0.15
proto-google-cloud-datastore-v1==0.90.0
proto-google-cloud-pubsub-v1==0.15.4
protobuf==3.6.1
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
Pygments==2.2.0
pytz==2018.5
PyVCF==0.6.8
PyYAML==3.13
requests==2.19.1
rsa==3.4.2
scandir==1.9.0
certifi==2018.8.24
simplegeneric==0.8.1
six==1.11.0
supervisor==3.3.1
tensorboard==1.10.0
tensorflow==1.4.1
tensorflow-tensorboard==0.4.0
termcolor==1.1.0
traitlets==4.3.2
typing==3.6.6
uritemplate==3.0.0
urllib3==1.23
virtualenv==16.0.0
wcwidth==0.1.7
Werkzeug==0.14.1

**Comment by gogasca** [comment]
Hi @Ankitagupta3988 


The `gcloud ml-engine jobs submit training` command is failing when invoking this function: 

`dispatch(args, model, cluster, task)` 

in the task.py script. This section of the code reads the arguments you just passed.

Questions:

1) If you try with original flowers dataset does it work?
2) When you tried the preprocess jobs with your images. Did you update the eval and train datasets to look as the original csv files but with your own information? 

gs://cloud-ml-data/img/flower_photos/sunflowers/14646281372_5f13794b47.jpg,sunflowers
gs://cloud-ml-data/img/flower_photos/sunflowers/1022552002_2b93faf9e7_n.jpg,sunflowers
gs://cloud-ml-data/img/flower_photos/sunflowers/50987813_7484bfbcdf.jpg,sunflowers

3) Can you paste the whole error?

**Comment by gogasca** [comment]
@Ankitagupta3988 will close this issue, feel free to reopen it if you still need help with this problem.
