### ISSUE TITLE
check_environment.py error:{ code :400 ~~

### ISSUE THREAD

**Issue by JaeinKim85** [GoogleCloudPlatform/cloudml-samples#26]
I had to perform the following commands to 

ERROR: Unable to list Cloud ML models: {
  "error": {
    "code": 400,
    "message": "Field: parent Error: Please make sure that Google Cloud Machine Learning API is enabled for the project.",
    "status": "FAILED_PRECONDITION",

I don't understand this mean...
Please I would like someone to provide a solution to this problem.

**Comment by chmeyers** [comment]
This means that the the Machine Learning API is not enabled for your Google Cloud Project.

A Project Owner can enable this API by going to:
https://console.cloud.google.com/apis/api/ml.googleapis.com/overview?project=YOUR_PROJECT_ID

replace YOUR_PROJECT_ID with your project's id.
