### ISSUE TITLE
Flowers update to latest tensorflow

### ISSUE THREAD

**Issue by lokeshsoni** [GoogleCloudPlatform/cloudml-samples#265]
Please update the flowers code to support all the latest libraries! The code when run in the same environment as prescribed throws an error on DataFlow console.

**Comment by gogasca** [comment]
@lokeshsoni thanks for contacting us, we will be updating our examples in the next coming weeks. I will update this thread. In the meantime, please take a look at existing issues, the error you report may be already reported before. (Update Apache Beam version to 2.6.0)

**Comment by gogasca** [comment]
I submitted a PR #312 which updates to latest CMEL supported version: 1.10
