### ISSUE TITLE
Flowers sample.sh needs to be updated for ML Engine GA, and require core/project_id is set

### ISSUE THREAD

**Issue by maclauss** [GoogleCloudPlatform/cloudml-samples#27]
I cannot submit a training job for the flowers sample anymore, it fails with the following error:
`ERROR: (gcloud.beta.ml.jobs.submit.training) value for field [projectsId] for in collection [ml.projects.jobs] is required but was not provided`

**Comment by puneith** [comment]
@maclauss We are working on fixing this. Thanks for your feedback.

**Comment by maclauss** [comment]
@puneith Awesome and thanks for your prompt reply, do you know when we can expect a fix and how we could go around it for the time being?

Thanks and awesome work on these examples!

**Comment by elibixby** [comment]
@maclauss I think this is just an issue with the sample.sh script and not with the actual training code. 

Try
```
gcloud config set project_id $MY_PROJECT_ID
```

Where you've set the project id that you want to deploy into and then rerun the script.

**Comment by puneith** [comment]
Thanks Eli! 

@maclauss So if you follow the instructions [here](https://cloud.google.com/blog/big-data/2016/12/how-to-classify-images-with-tensorflow-using-google-cloud-machine-learning-and-cloud-dataflow) and specifically this [link](https://cloud.google.com/ml-engine/docs/quickstarts/command-line) from the blog it will work fine.
