### ISSUE TITLE
Example showing use of a custom op using CUDA

### ISSUE THREAD

**Issue by davisking** [GoogleCloudPlatform/cloudml-samples#279]
Is it possible to use custom tensorflow ops with ML engine?  In particular, what is the procedure to include a custom op that uses CUDA? 

As a specific example, it would be great to have a complete example that showed how to train a simple model on ML engine that contained this custom cuda op: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/adding_an_op/cuda_op_kernel.cc.

**Comment by andrewferlitsch** [comment]
@puneith This request is a year old. Can we close it?

**Comment by andrewferlitsch** [comment]
@dizcology This request is a year old. Can we close it?

**Comment by dizcology** [comment]
Hi @davisking, I think your best choice is to to add the custom op and build the op library (following [this](https://www.tensorflow.org/guide/create_op)) in a docker image, then deploy it as a [custom container](https://cloud.google.com/ml-engine/docs/custom-containers-training) on AI Platform.
