### ISSUE TITLE
Notebooks not loading

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/cloudml-samples#281]
**Describe the bug**
New notebooks not loading in Github.

https://screenshot.googleplex.com/0Hz45Wk0DVj

**What sample is this bug related to?**

**Source code / logs**

**To Reproduce**
1.  Using Chrome 69.0
2. Click on Notebook
3. Gets error "Sorry something went wrong Reload?"

**Expected behavior**
Load Notebook

**Comment by dizcology** [comment]
Seems to work on both nbviewer and Colab.

https://nbviewer.jupyter.org/github/GoogleCloudPlatform/cloudml-samples/blob/master/census/estimator/trainer/task.ipynb

Perhaps an issue on GitHub's side.

**Comment by dizcology** [comment]
Appears to be a temporary thing.  As of now this notebook is rendered correctly on GitHub: https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/customestimator/trainer/task.ipynb
