### ISSUE TITLE
data file too large

### ISSUE THREAD

**Issue by dizcology** [GoogleCloudPlatform/cloudml-samples#283]
The IMDB data is rather large (32 mb of .pkl).  Instead of having the user clone the repo and then upload the data to GCS (https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/imdb#upload-the-data-to-a-google-cloud-storage-bucket), let's move the data on the publicly accessible bucket.

**Comment by gogasca** [comment]
Completed.
