### ISSUE TITLE
Unable to get "OBJECTIVE_VALUE" while performing Hyperparameter Tuning in CloudML

### ISSUE THREAD

**Issue by Aastha-Singh** [GoogleCloudPlatform/cloudml-samples#291]
**Error explained:**
Trying to run hyperparameter tuning in CloudML for the following values: _(maxTrials: 25, maxParallelTrials: 5)_. I can see that status for the tuning is green (successful). But there is no "OBJECTIVE_VALUE" in the Training output. Hence I am unable to find out which trial is the best one to choose.

Bug is related to Hyperparameter Tuning in CloudML.

**Observation:**
If I change the parameters for YAML file to _(maxTrials: 4, maxParallelTrials: 2)_, I can see the "OBJECTIVE_VALUE" in the Training output.

**System Information**
- python-version 3.5 

**Query:**
Is there any specific combination of parameters which are to be used if perfroming hyperparameter tuning in CLoudML ?

Screenshot for Expected output:
![expected](https://user-images.githubusercontent.com/13888481/47702137-0420a280-dc42-11e8-91c2-4bc6a7422e23.png)

Screenshot for Actual output:
![actual](https://user-images.githubusercontent.com/13888481/47702193-33371400-dc42-11e8-978e-10f2948e5c63.png)

**Comment by gogasca** [comment]
@Aastha-Singh thanks for reporting this issue, are you using any of the samples datasets in this folder?

We will be happy to see if we can reproduce the issue. Can you share?
-TF version
-CMLE version
-Dataset information
-Model information

Any other info which can help us troubleshoot/debug this problem will be helpful.

Thanks

**Comment by gogasca** [comment]
@Aastha-Singh looking to see if you still need help? We are interested in getting some extra details. Thanks

**Comment by Aastha-Singh** [comment]
@gogasca  thanks for helping me out. But I have found the solution to the problem. 
Looks like scale-tier is to be changed from BASIC to STANDARD_1 as I increase the number of parallel batches. 
Solved.
