### ISSUE TITLE
Python 3 compatibility issues (again)

### ISSUE THREAD

**Issue by cclauss** [GoogleCloudPlatform/cloudml-samples#294]
#287 was closed a bit too soon...

__lambda (x, y): x__ is a syntax error in Python 3 but __lambda x, y: x__ is not.

[flake8](http://flake8.pycqa.org) testing of https://github.com/GoogleCloudPlatform/cloudml-samples on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./criteo_tft/preprocess.py:102:49: E999 SyntaxError: invalid syntax
          | 'DropRandom' >> beam.FlatMap(lambda (k, vs): vs))
                                                ^
./iris/trainer/task.py:107:32: E999 SyntaxError: invalid syntax
                    key=lambda (class_name, class_index): class_index)]
                               ^
./reddit_tft/preprocess.py:118:49: E999 SyntaxError: invalid syntax
          | 'DropRandom' >> beam.FlatMap(lambda (k, vs): vs))
                                                ^
./movielens/preprocess.py:330:47: E999 SyntaxError: invalid syntax
          | 'DropRand' >> beam.FlatMap(lambda (k, vs): vs))
                                              ^
4     E999 SyntaxError: invalid syntax
4
```

**Comment by gogasca** [comment]
@cclauss thanks for reporting the issue again. Would you be fine submitting a new PR for this?
Thanks for your contributions.

**Comment by gogasca** [comment]
Will take a look at this one, some samples are marked as deprecated.

**Comment by gogasca** [comment]
All samples pointed out are deprecated. Closing issue
