### ISSUE TITLE
Code "flowers" example using other architectures

### ISSUE THREAD

**Issue by deramos** [GoogleCloudPlatform/cloudml-samples#307]
**Update the flower example to use other architectures.**
Example, Resnet, Inception_resnet, Mobilenet, Nasnet

**Comment by andrewferlitsch** [comment]
This sample seems very old-style (copyright 2016) and very "code-wordy". It could be greatly simplified, and the model architecture could be a cmd line argument, which is fetched as a pre-built model from the TF model zoo.

**Comment by gogasca** [comment]
@deramos We are working in a new sample for our new repo, will close this issue and tag you once samples is created
