### ISSUE TITLE
Add gcloud test for Census on CMLE 

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/cloudml-samples#311]
The kokoro sample script only tests local version. It will be great to add entry for running same tests on CMLE using gcloud. 

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/sample.sh

**Comment by nnegrey** [comment]
@gogasca Please take a look to see if this is feasible or close as `wont_fix`
Thanks

**Comment by nnegrey** [comment]
Update: we are woking to get kokoro support added to test for `gcloud local`

**Comment by gogasca** [comment]
Added test
