### ISSUE TITLE
Add a simple Dataflow example for census estimator.

### ISSUE THREAD

**Issue by fprost** [GoogleCloudPlatform/cloudml-samples#315]
I would like to add to a Dataflow pipeline for the estimator/ folder of census.

This pipeline would be relatively simple:
- Create a source to read the input csv.
- Split the csv into train/eval/test.
- Write back to csv (or tf-records).

The goal here is to demonstrate the basic Dataflow functionalities and highlight the typical code structure.

**Comment by happyhuman** [comment]
Thank you for your idea. We welcome such feature requests. Would you like to implement it and submit a Pull Request for a review and merge?

**Comment by fprost** [comment]
Absolutely, I will submit one soon.

Do you prefer 1 final submission or incremental improvements?

**Comment by gogasca** [comment]
@fprost Incremental PR may be a better idea.

**Comment by gogasca** [comment]
@fprost is this completed after latest PR?

**Comment by fprost** [comment]
Done. Thank you!
