### ISSUE TITLE
Add a RL sample for Cloud AI Blog

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/cloudml-samples#317]
**Is your feature request related to a problem? Please describe.**
RL for Blog

**Describe the solution you'd like**

**Key technologies to include**
* Workflow (Training, Serving, Complete Guide):
* ML Engine specfic features (CPU, GPU, HP Tuning, TPU):
* Framework (Tensorflow, Keras, scikit-learn, XGBoost, ...):
* Model:
* Dataset:

**Additional context**

**Comment by gogasca** [comment]
PR: https://github.com/GoogleCloudPlatform/cloudml-samples/pull/318

**Comment by nnegrey** [comment]
Fixed?
