### ISSUE TITLE
error in flowers/sample.sh

### ISSUE THREAD

**Issue by slcott** [GoogleCloudPlatform/cloudml-samples#32]
I get the following error when I run sample.sh from flowers sample:

```
gcloud ml-engine models create "$MODEL_NAME" \
  --region us-central1
ERROR: (gcloud.ml-engine.models.create) unrecognized arguments:
  --region (did you mean '--regions'?)
  us-central1
```

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/flowers/sample.sh#L69

should it be `regions us-central1`?

**Comment by mikehcheng2** [comment]
Thanks for reporting this, the change will be in soon.

**Comment by puneith** [comment]
@mikehcheng2 Can you pls update if this is fixed.

**Comment by puneith** [comment]
@slcott Its fixed now.
