### ISSUE TITLE
Verify XGBoost work in Python 3.5

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/cloudml-samples#321]
https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/xgboost

Internal reference: b/120086448

**Comment by nnegrey** [comment]
@gogasca @alecglassford @happyhuman 
Any updates on this?
Please take a look.

**Comment by nnegrey** [comment]
Ping

**Comment by happyhuman** [comment]
I tested. The notebooks for xgboost run with Python 3.5.4.
