### ISSUE TITLE
model name error in flowers/sample.sh

### ISSUE THREAD

**Issue by slcott** [GoogleCloudPlatform/cloudml-samples#33]
I get the following error:

```
gcloud ml-engine versions create "$VERSION_NAME" \
  --model "$MODEL_NAME" \
  --origin "${GCS_PATH}/training/model" \
  --runtime-version=1.0
ERROR: (gcloud.ml-engine.versions.create) FAILED_PRECONDITION: Field: version.deployment_uri Error: With v1 endpoint, the model directory gs://yt-8m-158920-ml/slcott/flowers_slcott_20170331_163758/training/model is expected to contain exactly one of thefollowing: saved_model.pb' file or 'saved_model.pbtxt' file.Please use SavedModel.
```

at: https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/flowers/sample.sh#L75

`MODEL_NAME` is `flowers` and `VERSION_NAME` is `v1` but it expects something else instead?

**Comment by mikehcheng2** [comment]
Can you inspect gs://yt-8m-158920-ml/slcott/flowers_slcott_20170331_163758/training/model to make sure it exists? That path is based on the JOB_ID, so if you reran sample.sh after noting the regions issue (thanks, we'll fix that up), that path may not be the correct one to the saved model.

**Comment by slcott** [comment]
Of course. You're totally right:

`flowers_slcott_20170331_163758/`

!=

`flowers_slcott_20170331_145423/`
