### ISSUE TITLE
 ps-replica-0 The scripts cygdb, cython and cythonize are installed in '/root/.local/bin' which is not on PATH.

### ISSUE THREAD

**Issue by hejabvbreus11** [GoogleCloudPlatform/cloudml-samples#336]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to convey here whether it occurred locally or on the server (CloudML Engine, Google Dataflow)

Im using ubuntu 16.04 and python 2.7.12 with Tensorflow 1.12.0 . I got this error log in the first place followed by ps-replica-0 Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. I have already upgraded all the packages in pip and my pip has already been up-to-date 18.1 
Here is my code:
```
gcloud ml-engine jobs submit training object_detection_`date +%s` \
   --runtime-version 1.8 \
  --job-dir=gs://tf_car_detector/train \
  --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz,dist/absl-py-0.6.1.tar.gz \
  --module-name object_detection.train \
  --region us-central1 \
  --config object_detection/samples/cloud/cloud.yml \
  -- \
  --train_dir=gs://tf_car_detector/train \
  --pipeline_config_path=gs://tf_car_detector/config/ssd_mobilenet_v1_coco.config \
  --no-warn-script-location
```

Anyone has any idea what can I modify to fix this problem. Also I appreciate it if you can tell me why the following log is labeled as error:
```
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235

totalMemory: 11.17GiB freeMemory: 11.10GiB

Truncated error message: Not found: /tmp/tmpGtak3K/model.ckpt-1_temp_71ac31b17ad44ff1afabce0e83592a37; No such file or directory


Command '['python', '-m', u'object_detection.model_main', u'--train_dir=gs://tf_car_detector/train', u'--pipeline_config_path=gs://tf_car_detector/config/ssd_mobilenet_v1_coco.config', u'--no-warn-script-location', '--job-dir', u'gs://tf_car_detector/train']' returned non-zero exit status 1
```

**What sample is this bug related to?**

**Source code / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**To Reproduce**

**Expected behavior**

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**:
- **Python version**:
- **Exact command to reproduce**:
- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```
**Additional context**

**Comment by nnegrey** [comment]
Hi, what sample is this related to?

**Comment by nnegrey** [comment]
Hi, any updates on this? Thanks!

**Comment by hejabvbreus11** [comment]
Hi, actually I am following this sample:
https://medium.com/coinmonks/modelling-transfer-learning-using-tensorflows-object-detection-model-on-mac-692c8609be40

**Comment by nnegrey** [comment]
Ah, I'm not familiar with that sample or the steps involved. 

But for Object Detection I do know of 2 blogs that have a similar flow, but slightly different from that one: 
1. https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
2. https://towardsdatascience.com/build-a-taylor-swift-detector-with-the-tensorflow-object-detection-api-ml-engine-and-swift-82707f5b4a56

I think it might be this one time setup steps:
1. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
2. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md

Related Issue: https://github.com/GoogleCloudPlatform/cloudml-samples/issues/225

**Comment by hejabvbreus11** [comment]
Yes, I also go through the two blogs you mention. Their flow is  similar and I am just stuck at last step-submit my training task to GCP.

**Comment by hejabvbreus11** [comment]
I also checked several issue threads here such as https://github.com/tensorflow/models/issues/3470

**Comment by nnegrey** [comment]
Did you complete this step? 
```export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim```

**Comment by hejabvbreus11** [comment]
Yes I follow https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
and I can run the model_builder_test.py

**Comment by nnegrey** [comment]
And all the steps in this one too?
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md

**Comment by nnegrey** [comment]
Hi, gonna close this issue for now, please feel free to reopen the issue if you are still having trouble. Thanks.

**Comment by arascan35** [comment]
I got this error too, anyone got a solution?
