### ISSUE TITLE
End-to-end flow with Google Cloud ML Engine

### ISSUE THREAD

**Issue by arashsa** [GoogleCloudPlatform/cloudml-samples#345]
**Is your feature request related to a problem? Please describe.**
A simple tutorial on how you can train, evaluate, tune, and serve models using the Python library. So a complete end-to-end tutorial/sample on how you would do everything with code.

**Describe the solution you'd like**
The solution would look like a tutorial that describes how you would do everything from a notebook. It would show how you would send a file with data to Google cloud. How you would send the training code to Google cloud. How you would initiate training with hyperparameter tuning. How you would take the best model and serve it. How you would automatically get the API endpoint for that model and start sending data for prediction. 

**Key technologies to include**
* Workflow (Training, Serving, Complete Guide):
The entire workflow.
* ML Engine specfic features (CPU, GPU, HP Tuning, TPU):
Nothing too specific here. Training with CPU and serving with as simple a way as possible.
* Framework (Tensorflow, Keras, scikit-learn, XGBoost, ...):
Keras.
* Model:
Any model will do. Keep it simple is probably best.
* Dataset:
Any dataset will do.

**Comment by gogasca** [comment]
Have you look at the Census example? That has an E2E flow.

**Comment by danicat** [comment]
Have you had a look at the links below?
Deployment: https://github.com/danicat/cloudml-samples/blob/master/notebooks/scikit-learn/Online%20Prediction%20with%20scikit-learn%20in%20CMLE.ipynb
HP Tuning: https://github.com/danicat/cloudml-samples/blob/master/notebooks/scikit-learn/Hyperparameter%20Tuning%20with%20scikit-learn%20in%20CMLE.ipynb
Training: https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Training%20with%20scikit-learn%20in%20CMLE.ipynb

**Comment by andrewferlitsch** [comment]
Since this is on-going notebook work for AI Platform, we can close the issue.
