### ISSUE TITLE
 Google Dataflow unsupported SDK version 0.5.5. error ": { "code": 400, "

### ISSUE THREAD

**Issue by CDC1688** [GoogleCloudPlatform/cloudml-samples#348]
**Describe the bug**
 It's related to Google Dataflow flowers example pre-process.py code. 
All I did before code was :
1)sudo pip install --upgrade -re requirements.txt
2)sudo pip install pip ==9.0.3 ( was to fix the --download problem with dataflow)

This should already upgraded apache-beam to version 2.8.0 and I don't understand why I stil have a google-cloud-dataflow==0.5.5 and gives me a unsupported error ? 

**Source code / logs**
zeyihe@cloudshell:~/cloudml-samples/flowers (nexgenai-224306)$ python trainer/preprocess.py \
>   --input_dict "$DICT_FILE" \
>   --input_path "gs://nexmodel/eval_set.csv" \
>   --output_path "${GCS_PATH}/preproc/eval" \
>   --cloud
/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/coders/typecoders.py:136: UserWarning: Using fallback coder for typehint: An
y.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be
 used instead.
Collecting google-cloud-dataflow==0.5.5
  Using cached https://files.pythonhosted.org/packages/18/18/e7d7a32f917d47bbcc7e3d5c9b60138a7d51adf04d155e0d400108915e79/google-cloud-d
ataflow-0.5.5.tar.gz
  Saved /tmp/tmpb53NfR/google-cloud-dataflow-0.5.5.tar.gz
Successfully downloaded google-cloud-dataflow
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "trainer/preprocess.py", line 496, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 492, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 399, in run
    configure_pipeline(p, in_args)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 170, in __exit__
    self.run().wait_until_finish()
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 163, in run
    return self.runner.run(self)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/runners/dataflow_runner.py", line 181, in run
    self.dataflow_client.create_job(self.job), self)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/utils/retry.py", line 167, in wrapper
    return fun(*args, **kwargs)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/internal/apiclient.py", line 430, in create_job
    return self.submit_job_description(job)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/internal/apiclient.py", line 451, in submit_job_description
    response = self._client.projects_jobs.Create(request)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apache_beam/internal/clients/dataflow/dataflow_v1b3_client.py", line 246, in Cre
ate
    config, request, global_params=global_params)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apitools/base/py/base_api.py", line 731, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apitools/base/py/base_api.py", line 737, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/zeyihe/.local/lib/python2.7/site-packages/apitools/base/py/base_api.py", line 604, in __ProcessHttpResponse
    http_response, method_config=method_config, request=request)
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://dataflow.googleapis.com/v1b3/projects/nexgenai-224306/jobs
?alt=json>: response: <{'status': '400', 'content-length': '342', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosnif
f', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control':'
private', 'date': 'Sun, 06 Jan 2019 13:16:52 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>,
 content <{
  "error": {
    "code": 400,
    "message": "(e9fa855cd9e14d77): The workflow was automatically rejected by the service because it uses an unsupported SDK version 0.
5.5. For a list of supported SDK versions, see: \nhttps://cloud.google.com/dataflow/support#support-status-for-dataflow-sdk-releases",
    "status": "INVALID_ARGUMENT"

**To Reproduce**
1. follow the flowers example code to set up envioronment 
2. sudo pip install --upgrade -re requirements.txt
3. sudo pip install pip ==9.0.3 ( was to fix the --download problem with dataflow)
4. Do the pre-process in dataflow : python trainer/preprocess.py \
>   --input_dict "$DICT_FILE" \
>   --input_path "gs://nexmodel/eval_set.csv" \
>   --output_path "${GCS_PATH}/preproc/eval" \
>   --cloud

**System Information**
- **Python version**: Using python 2.7.13
- Other version : as the requirements:
![image](https://user-images.githubusercontent.com/46419711/50736643-d2582900-11fa-11e9-9a63-bc950870736b.png)
apache-beam -2.8.0
tensorflow-1.10.0

**Comment by davidcavazos** [comment]
The `google-cloud-dataflow` package is now deprecated in favor of `apache-beam[gcp]`. Installing/upgrading `apache-beam` will **not** uninstall `google-cloud-dataflow`. Having said that, I'm unable to reproduce the issue, my jobs are succeeding even if I had `google-cloud-dataflow==0.5.5` preinstalled.

I noticed you are using `sudo` to install system-wide packages, which makes me think there might be some dependency conflict somewhere. I would suggest trying this from a clean virtual environment:
```bash
# Set up the virtual environment for Python 2.
pip2 install --user virtualenv
python2.7 -m virtualenv env
source env/bin/activate

# Install dependencies and run the training.
pip install --upgrade pip
pip install --upgrade -r requirements.txt
python trainer/preprocess.py \
  --input_dict "$DICT_FILE" \
  --input_path "gs://nexmodel/eval_set.csv" \
  --output_path "${GCS_PATH}/preproc/eval" \
  --cloud

# Deactivate the virtual environment.
deactivate
```

**Comment by nnegrey** [comment]
Closing this issue due to lack of updates, please feel free to re-open.

**Comment by CDC1688** [comment]
I didn't find a solutino to this problem. However I opened a new VM and the problem was solved.
