### ISSUE TITLE
get ERROR: gcloud crashed (BadStatusLine): '' when run in Google Cloud ML Engine

### ISSUE THREAD

**Issue by fatchur** [GoogleCloudPlatform/cloudml-samples#350]
**Describe the bug**
Hi all, i gott an ERROR: gcloud crashed (BadStatusLine): '' when running in Google Cloud ML Engine

**here are the step**
1. DATE=`date '+%Y%m%d_%H%M%S'`
2. export JOB_NAME=iris_$DATE
3. export GCS_JOB_DIR=gs://jobs/$JOB_NAME
4. export TRAIN_FILE=gs://cloud-samples-data/ml-engine/iris/iris_training.csv
5. export EVAL_FILE=gs://cloud-samples-data/ml-engine/iris/iris_test.csv
6. export TRAIN_STEPS=1000
7. export EVAL_STEPS=100
8. export REGION=us-central1

**Then, I run this**
gcloud ml-engine jobs submit training $JOB_NAME \
    --stream-logs \
    --runtime-version 1.10 \
    --job-dir $GCS_JOB_DIR \
    --module-name trainer.task \
    --package-path trainer/ \
    --region $REGION \
    -- \
    --train-file $TRAIN_FILE \
    --eval-file $EVAL_FILE \
    --train-steps $TRAIN_STEPS \
    --eval-steps $EVAL_STEPS

**This is my GCP version**
Google Cloud SDK 228.0.0
alpha 2018.11.09
app-engine-go
app-engine-java 1.9.70
app-engine-php " "
app-engine-python 1.9.80
app-engine-python-extras 1.9.74
beta 2018.11.09
bq 2.0.39
cbt
cloud-build-local
cloud-datastore-emulator 2.0.2
core 2018.12.07
datalab 20180823
docker-credential-gcr
gcd-emulator v1beta3-1.0.0
gsutil 4.34
kubectl 2018.09.17
pubsub-emulator 2018.02.02

**and got this**
ERROR: gcloud crashed (BadStatusLine): ''

Need help, please

**Comment by dizcology** [comment]
Hi @fatchur please include the full error message, thanks!

**Comment by gogasca** [comment]
Is gs://jobs/$JOB_NAME a valid name? Does "jobs" bucket, (gs://jobs) exists under your GCP project?

**Comment by fatchur** [comment]
I solved this issue by deleting the model, then redeploy.
