### ISSUE TITLE
Running the flowers example hangs / reports its going to take days to process

### ISSUE THREAD

**Issue by tayzlor** [GoogleCloudPlatform/cloudml-samples#36]
I'm trying to execute the flowers preprocessing example in Google Cloud Dataflow. 

It reports back that it is going to take over 15 days to complete the pre-processing of the images.

I'm following this example line for line - 

https://codelabs.developers.google.com/codelabs/cpb102-txf-learning/index.html?index=..%2F..%2Findex#4

I've also tried to follow along instructions from here and kick-off the pipeline from my machine using the gcloud CLI -

https://cloud.google.com/blog/big-data/2016/12/how-to-classify-images-with-tensorflow-using-google-cloud-machine-learning-and-cloud-dataflow

Looks like other users are reporting a similar issue (just 5 days ago) - 
https://plus.google.com/102370439237675402204/posts/5rbTgExPeUy

**Comment by tayzlor** [comment]
Closing this - it completed - still seems hugely slow though on a large dataset - I might need to tune some of the parameters

**Comment by joshgc** [comment]
Sorry about any performance issues you were facing.  Can you share how long it took?  How many images were you processing, if you weren't using the default flowers
