### ISSUE TITLE
PyTorch Docker image build freeze

### ISSUE THREAD

**Issue by dPacc** [GoogleCloudPlatform/cloudml-samples#370]
This issue seems to occur while running the Pytorch MNIST sample container on both CPU and GPU builds.
When the Docker image building reaches the part where it has to download the Pytorch image, the cloud editor freezes. This happened multiple times. However, the Tensorflow container seems to be running fine
![gcperror](https://user-images.githubusercontent.com/36117641/53410500-00cbd680-39ea-11e9-99e5-dd0333de5368.png)

**Comment by happyhuman** [comment]
Hi
Thanks for opening this issue. We will look into it. Did you have a chance to also run this locally and not in cloud shell?

**Comment by dPacc** [comment]
The image seems build successfuly on my local machine

**Comment by happyhuman** [comment]
May I suggest that you try and run your cloud shell in "Boost Mode" for this? I suspect you need more CPU power in your cloud shell for this to work. Here is a link for more information:
https://cloud.google.com/shell/docs/features#boost_mode

**Comment by dPacc** [comment]
That solved the issue. Thank you so much!
