### ISSUE TITLE
value error while running census exemple

### ISSUE THREAD

**Issue by Nine-s** [GoogleCloudPlatform/cloudml-samples#373]
Hello,
I am in the folder `cloudml-template/examples/census-classification/` and I try to run:
```
PACKAGE_PATH=trainer
TRAIN_FILES=data/train-data-*.csv
VALID_FILES=data/valid-data-*.csv
MODEL_DIR=trained_models/${MODEL_NAME}
echo ${MODEL_DIR}

gcloud ml-engine local train \
--module-name=trainer.task \
--package-path=${PACKAGE_PATH} \
-- \
--train-files=${TRAIN_FILES} \
--num-epochs=10 \
--train-batch-size=500 \
--eval-files=${VALID_FILES} \
--eval-batch-size=500 \
--learning-rate=0.001 \
--hidden-units="128,40,40" \
--layer-sizes-scale-factor=0.5 \
--num-layers=3 \
--job-dir=${MODEL_DIR}\
```
I am getting this error:

`ValueError: Either linear_feature_columns or dnn_feature_columns must be defined.`

How can I define it? And in which file from the trainer should I define it?
Thank you very much for your help!

**Comment by nnegrey** [comment]
Hi, did you modify the code at all?

**Comment by ksalama** [comment]
The code as-is should be working. Make sure that the linear_feature_columns and/or dnn_feature_columns in the create_classifier() method, in the model.py module are set. They should be set with the output of get_deep_and_wide_columns() method, in the featurizer.py module.

**Comment by Nine-s** [comment]
Hello again!
I haven't modified the code.
It was a tensorflow version issue. It works with tf==1.10.0 and not with tf==1.13.1.
Thank you for your answer.
