### ISSUE TITLE
Update deprecated-module running reddit example. 

### ISSUE THREAD

**Issue by IrribarraC** [GoogleCloudPlatform/cloudml-samples#374]
It is counter productive to learn of an example that will not be useful, The only thing I could rescue from reddit example is the bigquery data loading. Everything else seems to work entirely differently now.

An update of the reddit sample using supported modules on Tensorflow would be greatly appreciated, as it would fit a lot of problems of similar form. Especially when interacting smoothly with BigQuery.

**Comment by gogasca** [comment]
@IrribarraC unfortunately legacy examples won't be updated, we have plans to modularize the samples and show how to use specific features of CMLE, not TensorFlow in specific. If you need help with CMLE itself as a product we are happy to help. 
1. If you need help running TensorFlow code you can use this opportunity to work with TF team to use TF 2.0 which we do support in CMLE as well.
2. If you have an **specific** question of an error when you try to upgrade your sample we can take a look as well or you can also use stackoverflow to increase the audience.
