### ISSUE TITLE
Extract Movielens user_id and movie titles from online prediction output.

### ISSUE THREAD

**Issue by meirelon** [GoogleCloudPlatform/cloudml-samples#379]
How is the online prediction output supposed to be interpreted?

For example:
```
{
"classes":[1,2,3],
"scores":[0.001, 0.002, 0.003]
}
```

**Comment by sirtorry** [comment]
The prediction output is specified by your model. I believe in the example you provided it shows a classification and the confidence of such a classification. For example, 0.001 confidence that it is type 1, 0.002 that it's type 2, etc.

**Comment by thedriftofwords** [comment]
@meirelon Thanks for your question. I think @sirtorry has answered the main question - if not, feel free to ask follow-up questions.

We do need to improve how we explain this topic across all the samples, so I've opened issue #388.

**Comment by meirelon** [comment]
Thank you for your follow up response. Is there a best practice for attaching user_id to the prediction output?

**Comment by meirelon** [comment]
Is there a way to pass the user_id when making online and/or batch predictions?

**Comment by nnegrey** [comment]
I believe the model expects `user_id` to be sent as part of the feature set.

**Comment by andrewferlitsch** [comment]
closed SLO: no response by submitter
