### ISSUE TITLE
Scikit-learn CMLE trainer template and examples

### ISSUE THREAD

**Issue by cfezequiel** [GoogleCloudPlatform/cloudml-samples#386]
Problem:
As a user, I want to quickly figure out or be able to implement a sklearn ML pipeline for CMLE training/prediction on structured data.

**Describe the solution you'd like**
A sklearn CMLE model trainer similar to cloudml-samples/cloudml-template (trainer template for TensorFlow). Would also include working (runnable) example.

**Key technologies to include**
* ML Engine (training, online prediction, hyperparameter tuning)
* Framework: sklearn
* Model: classification/regression
* Dataset: structured - TBD

**Comment by sirtorry** [comment]
Please take a look at [cloudml-samples/sklearn/notebooks](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/sklearn/notebooks)

**Comment by cfezequiel** [comment]
Sorry for the delay in response. To clarify, I had an internal sync with @gogasca, et al. earlier this week about this, and they were okay to include this in sklearn/. Added value is showing how sklearn code can be structured into a trainer package for CMLE. We are also going to use relatively new sklearn features (e.g. compose) and building an end-to-end ML pipeline (train/eval, deploy, predict).
