### ISSUE TITLE
Improve explanations for prediction output

### ISSUE THREAD

**Issue by thedriftofwords** [GoogleCloudPlatform/cloudml-samples#388]
We should update every sample involving prediction with better explanations of:
* How to interpret prediction output
* How that's related to the way you set up your model

**Additional context**
See issue #379

**Comment by nnegrey** [comment]
@thedriftofwords Could you expand more on what you are looking for in future samples to do or close as `wont_fix` if infeasible. Thanks

**Comment by andrewferlitsch** [comment]
@nnegrey - too vague and too broad; should close as wont_fix.
