### ISSUE TITLE
ERROR: [ml-engine]The required property [region] is not currently set in Molecules

### ISSUE THREAD

**Issue by shiwang-gcp** [GoogleCloudPlatform/cloudml-samples#392]
**Describe the bug**
When ./run-cloud, got the following error:
ERROR: (gcloud.ml-engine.jobs.submit.training) The required property [region] is not currently set.

**What sample is this bug related to?**
molecules

**To Reproduce**
1. Follow the steps in https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/molecules/README.md.
2. Run command "./run-cloud --work-dir gs://<BUCKET>/cloudml-samples/molecules"
3. Got the error:
ERROR: (gcloud.ml-engine.jobs.submit.training) The required property [region] is not currently set.
It can be set on a per-command basis by re-running your command with the [--region] flag.

**Expected behavior**

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9 (stretch)
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**: Tensorflow
- **Python version**: 2.5
- **Exact command to reproduce**: ./run-cloud
- **Tensorflow Transform environment (if applicable, see below)**:

**Comment by jppr12** [comment]
Go to the function of training in the run-cloud file and add the region as in the image. I was with the same error and worked for me. ;)
![image](https://user-images.githubusercontent.com/22960250/57154721-70d35000-6dd1-11e9-9674-05f863aa5e59.png)

**Comment by nnegrey** [comment]
@davidcavazos PTAL

**Comment by nnegrey** [comment]
Thanks @davidcavazos.

@shiwang-gcp  going to close this now, but please feel free to reopen if the issue persists or open a new issue if you find something else. Thanks for filing this! :)
