### ISSUE TITLE
scikit-learn README.md has broken links to notebook examples

### ISSUE THREAD

**Issue by danicat** [GoogleCloudPlatform/cloudml-samples#394]
**Describe the bug**
All links in the README.md for scikit-learn are broken.

**What sample is this bug related to?**
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/sklearn/README.md

**To Reproduce**
Click on any link.

**Expected behavior**
The link should point to the right place :)

**Additional context**
I can submit a PR if you want. It seems that all notebook examples were moved to the root directory. But somehow there is still one (census data) at the `scikit-learn/notebooks` folder. What should be the correct file structure?

**Comment by danicat** [comment]
I've submitted a PR just to quick fix the README, but I think we should think better about this directory tree. And naming conventions.

**Comment by dizcology** [comment]
Thank you @danicat.  Your PR has been merged.

**Comment by gogasca** [comment]
Closing as discussed the new repo in meeting.
