### ISSUE TITLE
Hyper parameter tuner cannot find objective value in eager mode

### ISSUE THREAD

**Issue by katotetsuro** [GoogleCloudPlatform/cloudml-samples#408]
**Describe the bug**
When training job is running in eager mode, hyper parameter tuner cannot find objective value.
It happpens on the server(AI Platform).
![Screen Shot 2019-05-08 at 18 06 46](https://user-images.githubusercontent.com/364002/57366296-a9a06a00-71c1-11e9-9655-0efc5ea0661f.png)

**What sample is this bug related to?**
census/tf-keras

**Source code / logs**
I added this one line code
```
tf.enable_eager_execution()
```
at the beginning of training.

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/83d45fb189cf69d1716ee2d99c39a12580982827/census/tf-keras/trainer/task.py#L128

**To Reproduce**
1. Add `tf.enable_eager_execution()` 
2. exec this command from census/tf-keras directory.  `gcloud ai-platform jobs submit training [jobname] --module-name trainer.task --package-path trainer/ --runtime-version 1.13 --python-version 3.5  --job-dir [jobdir] --config hptuning_config.yaml`
3. after job has finished, `gcloud ai-platform jobs describe [jobname]` and there is no `finalMetric` entries.

**Expected behavior**
Hyper parameter tuner can find objective value.

**System Information**
- At client side, I use `Google Cloud SDK 245.0.0`

belows are AI platform's runtime infomation.
- Python-version=3.5
- runtime-version=1.13
- Framework is tf.keras

**Additional context**
I know eager mode isn't necessary for census/tf-keras example, but I want to use eager mode for my private project.
I guess this problem is related to difference of tensorboard's summary writer between eager and graph.

**Comment by gogasca** [comment]
Will try to reproduce this issue and get back to you this week, thanks

**Comment by gogasca** [comment]
@katotetsuro I was able to reproduce the problem, will get back to you.

**Comment by gogasca** [comment]
https://www.tensorflow.org/api_docs/python/tf/summary/FileWriter FileWriter is not compatible with eager execution. To write TensorBoard summaries under eager execution, use tf.contrib.summary instead.

**Comment by gogasca** [comment]
Take a look at this example: https://medium.com/@konpat/tensorflow-summary-api-v2-5fa760d04680

**Comment by andrewferlitsch** [comment]
Closed as answered.
