### ISSUE TITLE
__init__.py file missing

### ISSUE THREAD

**Issue by eeveeta** [GoogleCloudPlatform/cloudml-samples#42]
I'm trying to run the tutorial here: https://cloud.google.com/ml-engine/docs/how-tos/getting-started-training-prediction but I'm getting the following error:

`ERROR: (gcloud.ml-engine.jobs.submit.training) [/Users/Downloads/cloudml-samples-master 2/census/trainer] is not a valid Python package because it does not contain an         __init__.py file. Please create one and try again.`

If I navigate to the directory, there's an empty init file there, what could the problem be?

**Comment by puneith** [comment]
Are you running it from the estimator dir as this line in the tutorial says "cd cloudml-samples-master/census/estimator"?

**Comment by eeveeta** [comment]
@puneith This was the problem, thank you!
