### ISSUE TITLE
Submitting Training job from census tf-keras examples very slow?

### ISSUE THREAD

**Issue by datistiquo** [GoogleCloudPlatform/cloudml-samples#437]
Hey,

submitting training job to ai platform from the example 

```
! gcloud ai-platform jobs submit training $JOB_NAME \
  --package-path trainer/ \
  --module-name trainer.task \
  --region $REGION \
  --python-version 3.5 \
  --runtime-version 1.13 \
  --job-dir $JOB_DIR \
  --stream-logs
```

in 
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/tensorflow/getting-started-keras.ipynb

is very slow before any output log is shown?

Is this due to my machine?

**Comment by anifort** [comment]
Where are your data?

**Comment by datistiquo** [comment]
I am using the example from tutorial in above link. So ti will be downloaded.

**Comment by datistiquo** [comment]
It runs now for 2 hours without any log...

**Comment by nnegrey** [comment]
You can check the status of the job here: https://pantheon.corp.google.com/mlengine/jobs/my_first_keras_job/charts/cpu?project=YOUR_PROJECT_ID

**Comment by datistiquo** [comment]
I'll try oit again. Does the submitting job also depends on the chosen region?

**Comment by nnegrey** [comment]
Yes it does, please see here for more info: https://cloud.google.com/ml-engine/docs/tensorflow/regions
