### ISSUE TITLE
Security vulnerability message in dependencies for samples 

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/cloudml-samples#446]
**Describe the bug**
Security vulnerability message in dependencies for samples

**What sample is this bug related to?**
https://github.com/GoogleCloudPlatform/cloudml-samples

**Comment by andrewferlitsch** [comment]
If I recall, the security message relates to using TF 1.12 or earlier. GCP/AI supports TF 1.13. Perhaps all samples need to be upgraded to TF 1.13?

@puneith Perhaps you should think of someone to assign doing an inventory of which samples are pre-TF 1.13

**Comment by puneith** [comment]
https://github.com/GoogleCloudPlatform/cloudml-samples/network/alerts

**Comment by andrewferlitsch** [comment]
@puneith started the automated security fix on the alerts. Will come back before EOW to check of they got committed.

**Comment by andrewferlitsch** [comment]
made security fixes by hand
