### ISSUE TITLE
PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, error message '')

### ISSUE THREAD

**Issue by ohadperry** [GoogleCloudPlatform/cloudml-samples#45]
Ran the job successfully. 
Got to the visualization step
ran 
```
 tensorboard --logdir=$GCS_JOB_DIR
PermissionDeniedError: Error executing an HTTP request (HTTP response code 403, error code 0, error message '')
	 when reading gs://test-ml-ohad/jobs/job3
```
I have logged in with `gcloud` to the right account.

**Comment by ohadperry** [comment]
@elibixby  @joshgc any idea?

**Comment by joshgc** [comment]
Hi Ohad,

My guess is that the ACL's on either the bucket (to list objects) or on the files themselves are set up right.  Try these and lemme know if it helps

gsutil ch -u "${YOUR_ACCOUNT}:Rgs://test-ml-ohad
gsutil -m ch -r -u "${YOUR_ACCOUNT}:Rgs://test-ml-ohad/*

**Comment by elibixby** [comment]
TensorBoard uses [Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials)  to authenticate to GCS. So I would ensure you either have:

(a) run:
```
gcloud auth application-default login
```
Or,
(b) Set,
```
GOOGLE_APPLICATION_CREDENTIALS=/path/to/my/service_account.json
```

And as Josh mentioned ensure that the relevant account has access.

**Comment by puneith** [comment]
@ohadperry Closing this issue. Looks like its solved, but feel free to reopen if it still persists.
