### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)

### ISSUE THREAD

**Issue by rishab-sharma** [GoogleCloudPlatform/cloudml-samples#451]
**Bug Description**
I encounter this error, because of which the training breaks. Pytorch uses shared memory, because of which this issue arises.

**Possible Solution**
--ipc=host or --shm-size during the docker run may fix this, but we don't have to do docker run during gcloud training.

Please suggest a possible solution for this or fix your example accordingly.

Error: ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)

**Comment by nnegrey** [comment]
Hi, which sample are you referring to?

**Comment by rishab-sharma** [comment]
Hi, I am referring to the PyTorch custom container sample.

The sample fails in case of large models which has more requirements in terms of shared memory when the num_workers > 0 in the dataloader. The online suggests to increase the shm-size during docker run, but in case of gcloud training, we don't such option.

**Comment by rishab-sharma** [comment]
Ya, I am using a custom scale tier with a standard v100 GPU, which is enough for training large models as I recall from experience, but as my dataloader workers are 0, it takes more time for training, thus costing me more, and if I increase my num_workers, the training crashes at a random instance of the training routine.

If there could be a possible solution for this, please suggest

**Comment by rishab-sharma** [comment]
Also is there any way to pass arguments for the docker run, which might be automatically invoked by the **gcloud beta ai-platform jobs submit training command** ?

**Comment by andrewferlitsch** [comment]
The AI Platform product team is aware of the issue -- thanks for your patience.

**Comment by joaqo** [comment]
Awesome, thanks!

**Comment by andrewferlitsch** [comment]
closing as future feature requirement

**Comment by sshrdp** [comment]
This has been fixed in the service. Please reopen if you still have the issue.
