### ISSUE TITLE
Unexpected change of bucket path due to lstrip in PyTorch container example

### ISSUE THREAD

**Issue by lxuechen** [GoogleCloudPlatform/cloudml-samples#458]
I ran into this issue when I went over the tutorial given [here]( https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/pytorch/containers/hp_tuning).

Given how the model checkpoint copying is written [here]( https://github.com/GoogleCloudPlatform/cloudml-samples/blob/f8b7b5d2b822ccf8d98ed539de6110d6a6b85f19/pytorch/containers/hp_tuning/data_utils.py#L74), one would expect that all the checkpoints would be written to the path `job_dir/model_name`. This, however, is not the case due to the usage of `str.lstrip` on [this](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/f8b7b5d2b822ccf8d98ed539de6110d6a6b85f19/pytorch/containers/hp_tuning/data_utils.py#L81) line. Note that lstrip removes from left to right all the characters that appear in the argument, which itself is treated like a set, as opposed to a fixed token. So for instance, if `bucket_id` contains characters which appear in the remaining string of `bucket_path`, then those characters would get wiped out. Consider a simple example:
```
>>> 'abcaaaad'.lstrip('abc')
'd'
```

Perhaps a simple fix is to change this line to use something instead of lstrip, e.g. 
```
bucket_path = job_dir[len('{}/'.format(bucket_id)):]
```

**Comment by andrewferlitsch** [comment]
@dizcology PTAL
