### ISSUE TITLE
I can't access to my instance

### ISSUE THREAD

**Issue by policeme** [GoogleCloudPlatform/cloudml-samples#463]
**Describe the bug**
I can't access to my google cloud instance, after I enter the command like this**:gcloud compute ssh tpuv33 --zone=us-central1-a**, every instance has the same question in my two instances. what's wrong?

**Comment by gogasca** [comment]
For SSH access issues I recommend you to open a StackOverFlow question.
This repo is for Cloud AI samples specific questions.
