### ISSUE TITLE
Links in Online Prediction Section result in 404

### ISSUE THREAD

**Issue by skeller88** [GoogleCloudPlatform/cloudml-samples#465]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to convey here whether it occurred locally or on the server (AI Platform, Google Dataflow)

Follow both links [here](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Online%20Prediction%20with%20scikit-learn%20in%20CMLE.ipynb), and both result in 404.

**What sample is this bug related to?**

**Source code / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**To Reproduce**

**Expected behavior**

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**:
- **Python version**:
- **Exact command to reproduce**:
- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```
**Additional context**

**Comment by gogasca** [comment]
We renamed the Notebook as they contained spaces in the filename. 
You can still find notebooks here: https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/notebooks/scikit-learn
Will correct broken link sin docs.
