### ISSUE TITLE
census/tf-keras training tensorflow2

### ISSUE THREAD

**Issue by wutayng** [GoogleCloudPlatform/cloudml-samples#476]
**Is your feature request related to a problem? Please describe.**
The tutorial [here](https://cloud.google.com/ai-platform/docs/getting-started-keras) works correctly for the following command:
```
gcloud ai-platform local train \
  --package-path trainer \
  --module-name trainer.task \
  --job-dir local-training-output
```
Model training occurs and epochs are shown in the console.

However, I need this pipeline to work in tensorflow2. When I change [requirements.txt](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/tf-keras/requirements.txt) to tensorflow 2.1.0 and re-install, I get the following output for the gcloud command above
```
<subprocess.Popen object at 0x106cdb650>
```
Nothing else appears in the console and no training occurs.

**Describe the solution you'd like**
A (probably small) code change to make this tutorial work correctly for tensorflow 2

**Comment by gogasca** [comment]
I was able to reproduce issue, let me look into it and get back to you

**Comment by gogasca** [comment]
We opened internal issue. Looking at it now.

**Comment by kpe** [comment]
I have the same problem - no idea what it is

**Comment by gogasca** [comment]
We found the issue, it has to do with some warnings displayed when we grep the TF version will provide update about the fix soon. Thanks

**Comment by gogasca** [comment]
Issue was submitted it may make it for tomorrow SDK new version I will confirm it

**Comment by gogasca** [comment]
Issue is fixed in latest SDK version, thanks for reporting
