### ISSUE TITLE
Public google/cloud/ml/v1/job_service.proto is out of sync with json API

### ISSUE THREAD

**Issue by yonromai** [GoogleCloudPlatform/cloudml-samples#480]
**Describe the bug**
In the REST v1 API, The Job's ["TrainingInput" Resource](https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#traininginput) has a `pythonVersion` field. 

This field is unfortunately missing from the public [`google/cloud/ml/v1/job_service.proto`'s "TrainingInput"](https://github.com/googleapis/googleapis/blob/master/google/cloud/ml/v1/job_service.proto#L68) schema. 

It's shame a because this protobuf schema allows very nice type safety and convenience but it's not in sync with the API.

**What sample is this bug related to?**
None :\

**Additional context**
Hope this is the right place for this issue ([googleapis/googleapis](https://github.com/googleapis/googleapis) does not allow issues). If this is not the right place, please let me know where to file this issue.

**Comment by yonromai** [comment]
@dizcology Any update on this one?

**Comment by kweinmeister** [comment]
This issue is not related to the sample code in this repository, so I will go ahead and close it. If you are still interested in resolving the issue, the best path forward is to contact [Google Cloud Support](https://cloud.google.com/support).
