### ISSUE TITLE
Many links in readme is broken

### ISSUE THREAD

**Issue by Skorkmaz88** [GoogleCloudPlatform/cloudml-samples#489]
Some examples are : 

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Training%20with%20scikit-learn%20in%20CMLE.ipynb

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Hyperparameter%20Tuning%20with%20scikit-learn%20in%20CMLE.ipynb

https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/notebooks/scikit-learn/Online%20Prediction%20with%20scikit-learn%20in%20CMLE.ipynb

**Comment by Kazzpa** [comment]
Related [Commit](https://github.com/GoogleCloudPlatform/cloudml-samples/commit/e68d3f46e3efafbe0627d75ca866544015bd56a3)
other files  mentioned in the same commit could be affected too
Affected folder links https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/notebooks
