### ISSUE TITLE
Example/Template for Custom Container Online Prediction

### ISSUE THREAD

**Issue by adrianpgob** [GoogleCloudPlatform/cloudml-samples#495]
There is a lot of people with the same problem: `ERROR: (gcloud.beta.ai-platform.versions.create) Create Version failed. Bad model detected with error: Model requires more memory than allowed. Please try to decrease the model size and re-deploy. If you continue to experience errors, please contact support.` (I am one of those)

For this problem is being recommended to create a Custom Container, however, the process is tedious and there isn't any basic example or boilerplate(PyTorch Serve is an overkilling solution if you don't use Torch).

I think it could be very useful for the community if the Google team provides a preconfigured and basic Docker container with the best libraries for each requirement. 

Thank you

**Comment by kweinmeister** [comment]
Thank you for the suggestion. [Pre-built containers](https://cloud.google.com/vertex-ai/docs/predictions/pre-built-containers) for prediction are now available in Vertex AI.
