### ISSUE TITLE
Deploying just the pre-trained checkpoint files to CloudML

### ISSUE THREAD

**Issue by Shoshin23** [GoogleCloudPlatform/cloudml-samples#50]
Hey!

I'm trying to deploy just the model checkpoint files to cloud ML. I have the .ckpt file, .meta file and the lablemap.txt file for an inception network trained on the open images dataset. I'm looking for an option to just deploy them. I tried to work on it from the Prediction section of the Flowers post but I'm running into errors. 

Any pointers/posts that talk about deploying existing checkpoint files? 

Thanks!

**Comment by elmer-garduno** [comment]
The supported deployment artifact is the SavedModel, any reason why you wouldn't use one?

**Comment by puneith** [comment]
@Shoshin23 Did you try to create the service https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/README.md#create-a-prediction-service by first pushing the model binaries on GCS?

**Comment by elibixby** [comment]
@Shoshin23 @puneith You'll need to load the checkpoints into a graph and save them as a `saved_model` format. Saved model binaries have different metadata that is missing from a checkpoint (input and output tensors and graph tags).
