### ISSUE TITLE
ImportError: No module named apache_beam

### ISSUE THREAD

**Issue by yash26061981** [GoogleCloudPlatform/cloudml-samples#51]
Hi,

While running the flower sample, i am getting error:

python trainer/preprocess.py \
  --input_dict "$DICT_FILE" \
  --input_path "gs://cloud-ml-data/img/flower_photos/eval_set.csv" \
  --output_path "${GCS_PATH}/preproc/eval" \
  --cloud
Traceback (most recent call last):
  File "trainer/preprocess.py", line 71, in <module>
    import apache_beam as beam
ImportError: No module named apache_beam

I have followed the requirement guidelines. I dont know why i am getting this error. Any help please?

**Comment by mnanal** [comment]
I also see the same error while running flower sample.

**Comment by yash26061981** [comment]
@elibixby any idea to solve this issue.

**Comment by mnanal** [comment]
Hey Yash,
I was able to solve using following steps,

1) Read following nice article on virtualenv, this will help in later steps, 
https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/?utm_source=feedly

2) Create virtual environment ( Note I created it in cloudml-samples folder & named it env)
titanium-vim-169612:~/cloudml-samples$ virtualenv env

3) Activate virtual env
@titanium-vim-169612:~/cloudml-samples$ source env/bin/activate

4)  Install cloud-dataflow using following link:  (this brings in apache_beam)
https://cloud.google.com/dataflow/docs/quickstarts/quickstart-python

Now u can check that apache_beam is present in env/lib/python2.7/site-packages/
@titanium-vim-169612:~/cloudml-samples/flowers$ ls ../env/lib/python2.7/site-packages/

5)   Run the sample

At this point, I got an error about missing tensorflow.    I installed tensorflow in my virtualenv by using the link below (use installation steps for virtualenv),
https://www.tensorflow.org/install/install_linux#InstallingVirtualenv  

The sample seems to work now..

**Comment by yash26061981** [comment]
Thanks @mnanal . Yes this solves the issue. Just a bit more help. What if i want to use VGG16 instead of inception?

**Comment by mnanal** [comment]
sorry, I have no idea on how to use VGG16 instead of inception.  I assume it will involve changing the python code after doing above setup..

**Comment by puneith** [comment]
@yash26061981 Please take a look at Keras version https://www.tensorflow.org/api_docs/python/tf/contrib/keras/applications/VGG16 and I see coreTF versions as well if you search them.

**Comment by smikwazir** [comment]
Hey @mnanal - this solution worked for me too thanks

**Comment by irfanalee9** [comment]
Hi Everyone,
I did solve this problem by doing pip install apache-beam on command prompt in C:\Users\AwesomeUser\AppData\Local\Continuum\Anaconda2\Lib\site-packages and then restarted intellij and viola it worked. 
PS: I use windows system, love the challenge

**Comment by gunar** [comment]
For my problem, the solution was using the command `python3` instead of `python`:

```
$ python3 -m apache_beam.examples.wordcount …
```
