### ISSUE TITLE
Reddit_TFT Training error

### ISSUE THREAD

**Issue by AkhilSinghRana** [GoogleCloudPlatform/cloudml-samples#53]
I am trying to train Reddit dataset on the given trainer but, It gives an error in between. I was facing doing preprocessing as well and turns out the code need tensorflow-transform version 0.1.9 on both local systems as well as cloud. I am guessing the issue is because of the wrong tesnorflow version I am using for training (I am using tensorflow version 1.2 ) which version should I be using to make the example run. Also It would be nice if you upload Requrements.txt file

""Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 280, in <module> main() File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 276, in main output_dir=output_dir) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run return task() File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 281, in train monitors=self._train_monitors + extra_hooks) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 280, in new_func return func(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit loss = self._train_model(input_fn=input_fn, hooks=hooks) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 984, in _train_model _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss]) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 462, in run run_metadata=run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 786, in run run_metadata=run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 744, in run return self._sess.run(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 899, in run run_metadata=run_metadata)) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 465, in after_run raise NanLossDuringTrainingError NanLossDuringTrainingError: NaN loss during training.

**Comment by puneith** [comment]
@AkhilSinghRana Can you please try this with TF 1.0 and let us know if it works.

**Comment by AkhilSinghRana** [comment]
@puneith thanks for your response. It seems to be working with tensorflow1.0 but there are still some warnings related to GPU and float32 variables. Will let you know when the task gets completed. Thanks again.

**Comment by AkhilSinghRana** [comment]
@puneith Also do you have any idea how long it takes for the training to complete on cloud ? Or how many iterations will it continue for ? There is no accuracy report in between will it be shown at last! after complete training is done ? It just shows the Loss and step values. Hope it is working fine

**Comment by elibixby** [comment]
@AkhilSinghRana Number of steps is a specified value, check the defaults if you did not specify. Closing this for now.

**Comment by lukashes** [comment]
I have the same problem with tft 0.1.10 and tf 1.3. After reading this issue tried to install tf 1.0, but it does not help me.

`tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.`

**Comment by elibixby** [comment]
@lukashes Could you provide more complete logs in a gist or something? For what it's worth these examples have not yet been updated to TF 1.3 as CMLE does not yet have a TF 1.3 runtime, but 1.3 should be backwards compat with 1.2. Still without seeing more detailed logs the only recommendation I can make is try TF 1.2.
