### ISSUE TITLE
(Update canned estimator to 1.3) Monitors are deprecated. Please use tf.train.SessionRunHook.

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#61]
For problems running the sample code please provide the following information.

### System information
- Windows 10
- Tensorflow Version 1.2.0 (GPU)
- Python Version 3.6

### Describe the problem
I am trying to run the code locally in a jupyter notebook and try some different models (ie. only change the build estimator to a DNNClassifier for example) and I am getting a warning "Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py:268: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook."

which suggests that something in the code is still reliant on Monitors instead of tf.train.SessionRunHook.  I don't see any explicit use of Monitors, and I can't find where the default is monitors so I have not been able to diagnose where I need to use tf.train.SessionRunHook. Can anybody help to identify what modifications I would need to make to get past this warning or can it safely be ignored?

Thanks for the help!

**Comment by elibixby** [comment]
Thanks for the report. Our code currently uses the canned estimator `tf.contrib.learn.DNNCombinedLinearClassifier` which under the hood uses monitors until version 1.3. So you should see these warnings going away when 1.3 is released and we update these samples. @nkashy1  will close out this issue once we update to 1.3.

**Comment by puneith** [comment]
@jcomfort4 We have upgraded Census to TF1.4. Please try using that. Feel free to reopen or file another issue if you still encounter issues.
