### ISSUE TITLE
reddit_tft tokenization

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#64]
For the reddit_tft transformation, the tokenization is limited to tf.string_split() which splits on white space. Does tensorflow-transform have any ops to help with some other basic tokenization, such as first converting all text to lowercase and filtering out special characters? I can't find any samples that handle this preprocessing with tensorflow-transform. The [seq2seq](https://github.com/tensorflow/models/blob/master/tutorials/rnn/translate/data_utils.py) tutorial has some basic tokenization built in, but it's not clear to me if tft can replicate the preprocessing functionality that they use.

**Comment by elibixby** [comment]
You should be able to write your own transforms in with Apache Beam, that do whatever tokenization you want, however it's not guaranteed that there will be ops that support parity with your beam transforms in the serving graph. You could define your own ops or make a serving time proxy that does the tokenization. In any case this is a better discussion to have over at https://github.com/tensorflow/transform so I'm gonna close this issue.
