### ISSUE TITLE
"Skipping evaluation due to same checkpoint"

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#66]
### System information
- Mac OS, running via ML engine local train or cloud train
- TF 1.2
- Python 2.7

I posted this to [stackoverflow](https://stackoverflow.com/questions/45662282/google-cloud-ml-engine-skipping-evaluation-due-to-same-checkpoint) and got no responses, but the census sample is only running evaluations 1x per epoch even though I have set the min-eval-frequency flag.  Basically, the error message suggests that since the checkpoint is only being updated 1x per epoch, the evaluation is only being run 1x per epoch and the stackdriver logs output "Skipping evaluation due to same checkpoint..." every min-eval-frequency steps (every 100 steps with the default).  Is there an additional flag that must be set in the export strategy or something similar to either have checkpoints export more frequently? Alternatively, is there some way using min-eval-frequency to override this "skipping evaluation" so that it is done continuously?

Thanks!

**Comment by elmer-garduno** [comment]
Please take a look at the checkpoint_and_export flag on the Experiment class, it is a recent change so you might need to install tensorflow from source.

https://github.com/tensorflow/tensorflow/commit/9e6ee10fa85053cf4c237970a58f4ca2fe2c497e#diff-3c8e552e2ebc19d47327fa9087ee909eR927

**Comment by puneith** [comment]
@jcomfort4 The SO post answers this question. Also we moved Census to TF1.4 which has better & improved API. Please try it out and let us know if you still find the issue. Closing this issue for now.
