### ISSUE TITLE
Can't train locally

### ISSUE THREAD

**Issue by Ood-Tsen** [GoogleCloudPlatform/cloudml-samples#7]
I visit the website and try following the instruction to start training locally.

But I got an error "Invalid choice: 'local'".

Do I do anything wrong ?

```
$ gcloud beta ml local train --package-path=trainer --module-name=trainer.task
Usage: gcloud beta ml [optional flags] <group>
  group may be           jobs | models

*(BETA)* Cloud ML command groups.

global flags:
  Run `gcloud -h` for a description of flags available to all commands.

command groups:
  jobs                   *(BETA)* Cloud ML Jobs commands.
  models                 *(BETA)* Cloud ML Models commands.


For more detailed information on this command and its flags, run:
  gcloud beta ml --help

ERROR: (gcloud.beta.ml) Invalid choice: 'local'.

Valid choices are [jobs, models].
```

**Comment by chmeyers** [comment]
You are likely running an older version of gcloud, as the local option is relatively new.

Please run "gcloud components update"


To see what version of gcloud you have you can run "gcloud --version", I've verified that the latest version (135.0.0) has the local command.

**Comment by Ood-Tsen** [comment]
Thanks, it fixed after update to new version.
