### ISSUE TITLE
Document why tf.expand_dims is necessary in parse_csv

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#70]
I am looking through the parse_csv function in the census/customestimator/model.py and I'm having trouble understanding why the following code block is needed?

```
for key, value in six.iteritems(features):
    features[key] = tf.expand_dims(features[key], -1)
```

This appears in the parse_csv function for the canned estimator (in a different manner) but then does not appear in the parse_csv function for the tensorflowcore estimator. I think it would be helpful to have a snippet explaining why the expand_dims is needed and why the approach is different between custom and canned estimators.  

I am happy to post this question to stackoverflow if it is more applicable there, but it seemed directly relevant to the understanding of the sample code.

Thanks!

**Comment by elibixby** [comment]
From 1.2/when canned estimators used `tf.contrib.learn.Estimator`, estimator `model_fns` required Rank 2 tensors. This has been fixed in 1.3/`tf.estimator.Estimator`, so this line will be removed.
