### ISSUE TITLE
Run test.csv predictions on SavedModel?

### ISSUE THREAD

**Issue by jcomfort4** [GoogleCloudPlatform/cloudml-samples#71]
The census sample has a CSV serving input function and a test.csv file, but it's not clear in the documentation how to actually use the test.csv file to generate a prediction.  I tried creating a prediction service by following hte commands after setting `--export format CSV` when training, however I got the following error "Creating version (this might take a few minutes)......failed.                                                                             
ERROR: (gcloud.ml-engine.versions.create) Bad model detected with error:  "Error loading the model: Could not load model. " -- I believe that this is happening because the prediction service expects a JSON export format (not positive). Is there a way to use test.csv directly on the saved model without running the prediction service?

Thanks!

**Comment by elibixby** [comment]
The test.csv file is for the command line. 

```
gcloud ml-engine local predict --model-dir $MY_LOCAL_MODEL_DIR --text-instances test.csv
```

Should work. For the actual deployed service, you send CSV lines inside of the JSON you send to the REST service (although batch prediction allows you to pass CSV files directly through GCS.).

This is all in the docs here: https://cloud.google.com/ml-engine/docs/how-tos/online-predict and here
https://cloud.google.com/ml-engine/docs/how-tos/online-predict
