### ISSUE TITLE
Movielens preprocess takes years.

### ISSUE THREAD

**Issue by fanrice123** [GoogleCloudPlatform/cloudml-samples#76]
I ran this code on cloud compute engine. The problem is that one cpu is consumed to run the code and not really produced TFRecord. According to the monitor, no file has been written on disk as well since Disk IO is 0 bytes per second. Nearly half of RAM was still available.
I also tried to run this on my machine which result to suspend my machine after few second since all of my RAM had been consumed.
### System information
- **OS Platform and Distribution**: Linux Debian 9 
- **Machine type**：n1-standard-8 (8 vCPUs, 30 GB memory)

- **TensorFlow version**: 
    tensorflow==1.2.0
    tensorflow-tensorboard==0.1.6
    tensorflow-transform==0.1.10
    apache-beam==2.1.0
- **Python version**: 2.7

python preprocess.py --input_dir $INPUT_DIR --output_dir $OUTPUT_DIR --percent_eval 20 --project_id $PROJECT --negative_sample_ratio 1 --negative_sample_label 0.0 --eval_type ranking --eval_scor
e_threshold 4.5 --num_ranking_candidate_movie_ids 1000 --partition_random_seed 0
No handlers could be found for logger "oauth2client.contrib.multistore_file"
/usr/local/lib/python2.7/dist-packages/apache_beam/coders/typecoders.py:135: UserWarning: Using fallback coder for typehint: Any.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
WARNING:tensorflow:From /home/fchunhuei/cloudml-samples/movielens/preproc/movielens.py:259: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`.
WARNING:tensorflow:From /home/fchunhuei/cloudml-samples/movielens/preproc/movielens.py:259: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`.
WARNING:tensorflow:From /home/fchunhuei/cloudml-samples/movielens/preproc/movielens.py:259: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`.
WARNING:tensorflow:From /home/fchunhuei/cloudml-samples/movielens/preproc/movielens.py:259: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`.
WARNING:tensorflow:From /home/fchunhuei/cloudml-samples/movielens/preproc/movielens.py:259: string_to_index_table_from_tensor (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-04-10.
Instructions for updating:
Use `index_table_from_tensor`.
2017-09-10 23:16:00.308020: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-10 23:16:00.308072: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-10 23:16:00.308081: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-10 23:16:00.308088: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-10 23:16:00.308095: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
/usr/local/lib/python2.7/dist-packages/apache_beam/coders/typecoders.py:135: UserWarning: Using fallback coder for typehint: Union[float, int, long, str, unicode].
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
/usr/local/lib/python2.7/dist-packages/apache_beam/coders/typecoders.py:135: UserWarning: Using fallback coder for typehint: <type 'NoneType'>.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)

**Comment by elmer-garduno** [comment]
Hi @fanrice123, thanks for the feedback let us take a look at what's going on.

**Comment by gary-domain** [comment]
5 hours and counting for me

**Comment by puffler** [comment]
Same for me. I've had the job running locally for about 3 hours now and no results. I also spun up a Dataflow job with 200 workers (and a ton of resources) who ran for 1 hour and 1 minute until it failed with the following error:

Workflow failed. Causes: (e2a3592db2c9f9c3): The Dataflow appears to be stuck. Please reach out to the Dataflow team at http://stackoverflow.com/questions/tagged/google-cloud-dataflow.

**Comment by elmer-garduno** [comment]
Did you specified the --cloud and --project_id for the pipeline to run on cloud?

**Comment by puffler** [comment]
Yes, this command was run from Datalab inside the project:
```
!python preprocess.py --input_dir $GCS_TRAINING_INPUT_DIR \
                     --output_dir $PREPROCESS_OUTPUT \
                     --percent_eval 20 \
                     --project_id $PROJECT \
                     --negative_sample_ratio 1 \
                     --negative_sample_label 0.0 \
                     --eval_type ranking \
                     --eval_score_threshold 4.5 \
                     --num_ranking_candidate_movie_ids 1000 \
                     --partition_random_seed 0 \
                     --cloud
```
echo'ing the variables provides these values
$PROJECT: the project I use
$GCS_TRAINING_INPUT_DIR: gs://bucket/folder_with_csv_files
$PREPROCESS_OUTPUT: gs://bucket/some_output_folder

**Comment by elmer-garduno** [comment]
Do you know which version of apache-beam[gcp] is available on the datalab?

**Comment by puffler** [comment]
`!pip freeze
apache-beam==2.1.1
avro==1.8.2
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0rc1
beautifulsoup4==4.6.0
bleach==1.5.0
brewer2mpl==1.4.1
bs4==0.0.1
cachetools==2.0.1
certifi==2017.7.27.1
chardet==3.0.4
configparser==3.5.0
crcmod==1.7
cycler==0.10.0
datalab==1.0.1
decorator==4.1.2
dill==0.2.6
entrypoints==0.2.3
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
gapic-google-cloud-pubsub-v1==0.15.4
gapic-google-logging-v2==0.9.3
gapic-google-pubsub-v1==0.9.3
ggplot==0.6.8
google-api-python-client==1.6.2
google-apitools==0.5.10
google-auth==1.0.2
google-auth-httplib2==0.0.2
google-cloud==0.19.0
google-cloud-bigquery==0.25.0
google-cloud-core==0.25.0
google-cloud-dataflow==2.0.0
google-cloud-pubsub==0.26.0
google-gax==0.15.15
googleapis-common-protos==1.5.2
googledatastore==7.0.1
grpc-google-iam-v1==0.11.1
grpc-google-logging-v2==0.9.3
grpc-google-pubsub-v1==0.9.3
grpcio==1.4.0
html5lib==0.9999999
httplib2==0.9.2
idna==2.6
ipykernel==4.5.2
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==6.0.0
Jinja2==2.8
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-core==4.3.0
lime==0.1.1.23
Markdown==2.2.0
MarkupSafe==1.0
matplotlib==1.5.3
mistune==0.7.4
mltoolbox-datalab-classification-and-regression==1.0.1
mltoolbox-datalab-image-classification==0.2
mock==2.0.0
nbconvert==5.2.1
nbformat==4.3.0
networkx==1.11
nltk==3.2.1
notebook==4.2.3
numpy==1.11.2
oauth2client==2.2.0
olefile==0.44
pandas==0.19.1
pandas-profiling==1.4.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.4.1
pbr==3.1.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.1
plotly==1.12.5
ply==3.8
prompt-toolkit==1.0.15
proto-google-cloud-datastore-v1==0.90.0
proto-google-cloud-pubsub-v1==0.15.4
protobuf==3.4.0
psutil==4.3.0
ptyprocess==0.5.2
pyasn1==0.3.2
pyasn1-modules==0.0.11
Pygments==2.1.3
pyparsing==2.2.0
python-dateutil==2.5.0
pytz==2016.7
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
requests==2.18.4
rsa==3.4.2
scandir==1.5
scikit-image==0.13.0
scikit-learn==0.18.2
scipy==0.18.0
seaborn==0.7.0
simplegeneric==0.8.1
simplejson==3.11.1
singledispatch==3.4.0.3
six==1.10.0
statsmodels==0.6.1
subprocess32==3.2.7
sympy==0.7.6.1
tensorflow==1.2.0
tensorflow-transform==0.1.10
terminado==0.6
testpath==0.3.1
tornado==4.4.2
traitlets==4.3.2
uritemplate==3.0.0
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
widgetsnbextension==2.0.0
`

**Comment by puffler** [comment]
I just managed to get it working running locally on 100k samples. It took about 400 seconds.

The Dataflow job is still not working however. Even when running it with 2(!) samples from the ratings csv. Dataflow does nothing and times out after 1 hour.

**Comment by sstrato** [comment]
Same issue
strace says like below ( and it's repeated)

`
stat("/home/movielens/movielens/share/locale/en_US.ISO8859-1/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/usr/share/locale-langpack/en_US.ISO8859-1/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/home/movielens/movielens/share/locale/en_US/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/usr/share/locale-langpack/en_US/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/home/deploy/movielens/movielens/share/locale/en.ISO8859-1/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/usr/share/locale-langpack/en.ISO8859-1/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/home/movielens/movielens/share/locale/en/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/usr/share/locale-langpack/en/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/home/movielens/movielens/share/locale/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
stat("/usr/share/locale-langpack/LC_MESSAGES/messages.mo", 0x7fc941ff84f0) = -1 ENOENT (No such file or directory)
`

**Comment by elmer-garduno** [comment]
@aaltay any idea what can be going wrong with this stuck dataflow jobs?

**Comment by aaltay** [comment]
@SebastianLshft7 If nothing is processed (even 2 records), it is likely that there is a setup error (e.g. wrong dependencies, failed to install something etc.). Could you look at the stackdriver logs and see if there are any errors. If that does not lead to anything, we can look at the job if you have a dataflow job id.

@sstrato Are you running on Dataflow, or are you running things locally?

**Comment by sstrato** [comment]
@aaltay  it's from local runner

**Comment by aaltay** [comment]
@sstrato How much data you are trying to process in the local runner? Currently local runner (`DirectRunner`) is not optimized and is limited in the amount of data it can process.

**Comment by sstrato** [comment]
@aaltay I try the movielens 20m model ( about 510MB ) on my local machine. I doubted the runner's capacity is limited to memory size. 
If there's size limitation on local runner, it would be better to write some information about that on README file

**Comment by aaltay** [comment]
Beam DirectRunner for python struggles with inputs > 100MB in general. It does not have README file, but it has a page on Beam website (https://beam.apache.org/documentation/runners/direct/). It does not have an explicit size limit, but we can add a note there about it.

**Comment by elmer-garduno** [comment]
Thanks @aaltay, I will also add a note on this sample explaining that the DirectRunner should not be used for the large Movielens dataset.

**Comment by sstrato** [comment]
@aaltay @elmer-garduno  the thing is that this sample using large data set. i think you'd better using 100k movielens model which is just few MB.

**Comment by elmer-garduno** [comment]
Thanks for the feedback, it should be made more prominent that the local run should use the smaller dataset. 

https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/movielens#local-run

And the cloud version should be used to process the large dataset

https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/movielens#cloud-run

I'll submit a PR.

+ @puneith

**Comment by elmer-garduno** [comment]
Thanks @sstrato created https://github.com/GoogleCloudPlatform/cloudml-samples/pull/102/files

**Comment by puneith** [comment]
In addition to @elmer-garduno change we also have made few changes in the versioning and verified it works. It should work for you now so closing this issue. Please feel free to reopen if it doesn't.

**Comment by daltonj** [comment]
Is this resolved for the cloud version? I'm still seeing quite long extraction times for the large dataset.  I have eight jobs that have spent over two hours running on it according to cloud console.
