### ISSUE TITLE
Unable to create model version - Model artifacts size exceeds 1GB

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/cloudml-samples#8]
Hi,
I'm trying to deploy a version of my model with cloud ml. My training artifacts are 3GB. 
I get the following error message. I was wondering if there was a way around this.

ERROR: (gcloud.beta.ml.models.versions.create) FAILED_PRECONDITION: Field: version.deployment_uri Error: The total size of files in gs://model-export-bucket/ is 3118066753 bytes, which exceeds the allowed maximum of 1073741824 bytes.

Thanks,
Surya

**Comment by elmer-garduno** [comment]
Hi Surya, let us take a look.

@bhupc

**Comment by bhupc** [comment]
Hi Surya,
The current model deployment will fail because it expects a maximum of 1GB of total model artifacts.  if you don't mind me asking, what kind of model is this?

One a side note, are you planning to do a batch prediction on the deployed model or were you planning to do online prediction with this model?

**Comment by sprakash3** [comment]
Hi,
This is a NER model. The word vectors contribute significantly to the size of the model. The idea is to do an online prediction.

**Comment by sprakash3** [comment]
@bhupc I'm curious to know why 1GB was set as a limit. Also is there a way to got around this issue ?

**Comment by bhupc** [comment]
Thanks for the information. Online prediction is in alpha and 1GB till now
has served well while preventing any abuse of the system. If use cases and
users start demanding for more, yes, we will consider higher limit

The only workaround is to reduce the model size.  Is that something you are
willing to consider?

**Comment by dannybtran** [comment]
Was this lowered recently?  I've received this error message but with a limit of 250MiB.

**Comment by rhaertel80** [comment]
This limit has been lowered to 250MiB for the time being. The load time for larger can be high, making it difficult to auto-scale the model in response to increased traffic.

We are working to improve load times and scaling characteristics and will adjust the limit as we make progress.

If you're interested in trying out the system with larger models (and accepting the limitations) we can consider increasing the limit for your particular project. Send email to cloudml-feedback@ with the request, a brief explanation of what type of model you're using and how big it is, and an explanation of why it can't be smaller (have you considered: fewer parameters, quantization, etc.).

**Comment by puneith** [comment]
Closing this issue as @rhaertel80 has very appropriately answered the topic.
