### ISSUE TITLE
handling nulls?

### ISSUE THREAD

**Issue by ericsheetz** [GoogleCloudPlatform/cloudml-samples#84]
I tried to see what would happen if my data is more sparse than the census sample and a continuous feature like age were null in a prediction test.  Every way in which I try to represent a null results in errors that tell me my modification of instances.json is not valid json.

**Comment by ericsheetz** [comment]
I've learned that linear models require no nulls.  I'm now experimenting with how to replace the nulls with values that minimize impact.  My models are now training.  It would be nice if the error pointed the user in the direction of engineering their data to not have nulls.

**Comment by puneith** [comment]
@ericsheetz Thanks for reporting. Ack and please feel free to send a PR if you already have a fix.
