### ISSUE TITLE
Remote Distributed Training not working 

### ISSUE THREAD

**Issue by dexterchan** [GoogleCloudPlatform/cloudml-samples#87]
Remote Distributed with parameter scale-tier = STANDARD_1 failed to run with Google ML engine.
From the log, seem the replicas is cleaning up the cloud storage storing the package after master finish initialization....

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS, High Serra, pushing to Google Cloud ML
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7
- **Exact command to reproduce**: gcloud ml-engine jobs submit training census_20171005_162623 --stream-logs --scale-tier STANDARD_1 --staging-bucket gs://dextest --runtime-version 1.2 --job-dir gs://dextest/census_20171005_162623 --module-name trainer.task --package-path trainer/ --region us-central1 -- --train-files gs://cloudml-public/census/data/adult.data.csv --eval-files gs://cloudml-public/census/data/adult.test.csv --train-steps 1000 --eval-steps 100
- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
the sample code, and whether it occurred locally or on the server (CloudML Engine,
Google Dataflow)

For problems running the sample code please provide the following information.
When running tensorflow with REMOTE distributed command: after specifying "scale-tier STANDARD_1". Batch failed to run.... Now, I can ONLY run with simple SINGLE NODE "scale-tier=BASIC"

gcloud ml-engine jobs submit training census_20171005_162623 --stream-logs --scale-tier STANDARD_1 --staging-bucket gs://dextest --runtime-version 1.2 --job-dir gs://dextest/census_20171005_162623 --module-name trainer.task --package-path trainer/ --region us-central1 -- --train-files gs://cloudml-public/census/data/adult.data.csv --eval-files gs://cloudml-public/census/data/adult.test.csv --train-steps 1000 --eval-steps 100

The replica worker 1 exited with a non-zero status of 1. Termination reason: Error.

From the log: Retrying after gsutil exception Command '['gsutil', '-q', 'cp', u'gs://dextest/census_20171005_161531/2211a814b974edbc3defee855046dd8e801393b7ff8154b084b081322167fe90/trainer-0.0.0.tar.gz', u'trainer-0.0.0.tar.gz']' returned non-zero exit status 1.

The Master did SUCCESSFULLY initialized and copued the package "trainer-0.0.0.tar.gz" However, issue happened when replicas copying package for the run. It seems that the ML workflow FAILED to handle the cleanup in replicas.... The replicas tried to clean the job directory "gs://dextest/census_20171005_162623" again before running.

the error happened after master copy the package and the replicas FAILED to pick up the package for running.

I CommandException: No URLs matched: gs://dextest/census_20171005_161531/2211a814b974edbc3defee855046dd8e801393b7ff8154b084b081322167fe90/trainer-0.0.0.tar.gz E Retrying after gsutil exception Command '['gsutil', '-q', 'cp', u'gs://dextest/census_20171005_161531/2211a814b974edbc3defee855046dd8e801393b7ff8154b084b081322167fe90/trainer-0.0.0.tar.gz', u'trainer-0.0.0.tar.gz']' returned non-zero exit status 1. undefined

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by puneith** [comment]
@dexterchan There was a bug introduced due to a change and I have fixed it. In the mean time the STANDARD_1 is taking a longer time for TFCore example and I am looking into it.

**Comment by puneith** [comment]
@dexterchan This specific issue has been fixed in the code and the separate issue of code taking longer time I will need to verify, so closing this.
