### ISSUE TITLE
Wrongly identify unsupported TF version

### ISSUE THREAD

**Issue by larry-fuy** [GoogleCloudPlatform/cloudml-samples#9]
To check the development environment through [check_environment.py](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/tools/check_environment.py) after intalled TF from source, it spits out an error message "ERROR: Unsupported TensorFlow version: 0.12.head (minimum 0.11.0rc0)." The reason is that in the [code](
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/tools/check_environment.py#L58) parse_version cannot identify correctly the version format like "0.12.head" due to [PEP 440](https://www.python.org/dev/peps/pep-0440/#normalization).

**Comment by joshgc** [comment]
Hey Larry,

Is this still an issue?  Sorry to get back to you so late, but this should be fixed now.  If you are still the same problem, please let me know what environment you are running and consider posting the output of `pip freeze`.  Thanks so much for playing with our samples!

Josh
